apache/incubator-quickstep

query_execution/BlockLocator.cpp, query_execution/BlockLocator.hpp, query_execution/CMakeLists.txt, query_execution/QueryExecutionMessages.proto, query_execution/QueryExecutionTypedefs.hpp, query_execution/tests/BlockLocator_unittest.cpp, storage/CMakeLists.txt, storage/StorageManager.cpp, storage/StorageManager.hpp
As a part of Data Exchange service, we need the `BlockLocator` to determine the block locations, and retrieve the network address of peers.
=> Added BlockLocator.

build/profile_build.sh
Adding a utility script that I find helpful.
=> Add a shell script that logs the build process for later profiling

NOTICE
Part I of a sequence of changes to bring the NOTICE and Copyright inline with ASF guidelines.
=> Fix the NOTICE file

query_optimizer/logical/Sort.hpp, query_optimizer/resolver/Resolver.cpp
Added move constructor in optimizer::logical::Sort.
=> Minor Change: Use move semantics when constructing optimizer::logical::Sort

query_optimizer/resolver/Resolver.cpp
Added move semantic in the constructor of `Resolver::WindowPlan`.
=> Minor Change: Added move semantic in Resolver::WindowPlan

query_optimizer/CMakeLists.txt, query_optimizer/ExecutionGenerator.cpp, query_optimizer/physical/CMakeLists.txt, query_optimizer/physical/PhysicalType.hpp, query_optimizer/physical/WindowAggregate.cpp, query_optimizer/physical/WindowAggregate.hpp, query_optimizer/strategy/CMakeLists.txt, query_optimizer/strategy/OneToOne.cpp, query_optimizer/tests/physical_generator/Select.test
- The PhysicalGenerator could now generate a physical plan for window aggregate function using OneToOne strategy. 
- The ExecutionGenerator will catch window aggregate function and throw an exception.
=> QUICKSTEP-20: PhysicalGenerator support for Window Aggregation

relational_operators/HashJoinOperator.cpp, relational_operators/HashJoinOperator.hpp
=> Remove unused vector_based HashJoin collector type

types/operations/unary_operations/NumericCastOperation.hpp
[Link to JIRA request.](https://issues.apache.org/jira/browse/QUICKSTEP-33)
=> QUICKSTEP-33: Fixed the bug in NumericCast.

DEV_README.md, README.md
Besides adding a quick start guide, also moved the old README to a developer README.
=> Add a quick start guide.

types/operations/comparisons/BasicComparison.cpp, types/operations/comparisons/BasicComparison.hpp, types/operations/comparisons/CMakeLists.txt, types/operations/comparisons/ComparisonUtil.hpp, types/operations/comparisons/LiteralComparators.hpp, types/operations/comparisons/tests/Comparison_unittest.cpp
=> Added Comparisons for the Date Type.

CMakeLists.txt, query_execution/CMakeLists.txt, query_execution/QueryExecutionMessages.proto, query_execution/QueryExecutionTypedefs.hpp, query_execution/QueryManagerDistributed.cpp, query_execution/QueryManagerDistributed.hpp, query_execution/ShiftbossDirectory.hpp
=> Added QueryManagerDistributed.

query_execution/CMakeLists.txt, query_execution/ForemanSingleNode.cpp, query_execution/ForemanSingleNode.hpp, query_execution/PolicyEnforcerBase.cpp, query_execution/PolicyEnforcerBase.hpp, query_execution/PolicyEnforcerSingleNode.cpp, query_execution/PolicyEnforcerSingleNode.hpp
=> Introduced PolicyEnforcerBase and its single-node implementation.

types/README.md
This adds a developer's README for the basic classes in the types module. More docs on containers and operations will be forthcoming.
=> Added README for types module.

query_execution/QueryExecutionMessages.proto, query_execution/QueryManagerDistributed.cpp, query_execution/QueryManagerDistributed.hpp, query_execution/Shiftboss.cpp
=> Processed InitiateRebuild message for the distributed version.

query_optimizer/QueryProcessor.cpp, query_optimizer/QueryProcessor.hpp
This PR reverted `optimizer` per query, and avoids memory leaks if encountered any exceptions.
=> Refactored QueryProcessor.

query_execution/CMakeLists.txt, query_execution/PolicyEnforcerBase.cpp, query_execution/PolicyEnforcerBase.hpp, query_execution/PolicyEnforcerDistributed.cpp, query_execution/PolicyEnforcerDistributed.hpp, query_execution/QueryExecutionMessages.proto, query_execution/QueryExecutionTypedefs.hpp, query_execution/QueryManagerBase.cpp, query_execution/QueryManagerBase.hpp
The functionality was tested by #70.
=> Added PolicyEnforcer implementation for the distributed version.

query_execution/CMakeLists.txt, query_execution/ForemanDistributed.cpp, query_execution/ForemanDistributed.hpp
Assigned to @hbdeshmukh. Thanks!
This is an initial version that accepts only one `Shiftboss`, tested by #94 while replaced #85.
=> Added ForemanDistributed.

query_execution/ForemanSingleNode.cpp, query_execution/ForemanSingleNode.hpp, query_execution/PolicyEnforcerBase.hpp, query_execution/QueryExecutionTypedefs.hpp, utility/CMakeLists.txt, utility/ExecutionDAGVisualizer.cpp
This PR is to fix the IWYU issues as commented in PR #76. @zuyu
=> Fix IWYU for ExecutionDAGVisualizer

cli/tests/CMakeLists.txt, cli/tests/CommandExecutorTestRunner.cpp, cli/tests/CommandExecutorTestRunner.hpp, query_optimizer/CMakeLists.txt, query_optimizer/ExecutionGenerator.cpp, query_optimizer/ExecutionGenerator.hpp, query_optimizer/LogicalGenerator.cpp, query_optimizer/LogicalGenerator.hpp, query_optimizer/Optimizer.cpp, query_optimizer/Optimizer.hpp, query_optimizer/OptimizerContext.hpp, query_optimizer/QueryProcessor.cpp, query_optimizer/QueryProcessor.hpp, query_optimizer/resolver/Resolver.cpp, query_optimizer/resolver/Resolver.hpp, query_optimizer/tests/CMakeLists.txt, query_optimizer/tests/ExecutionGeneratorTestRunner.cpp, query_optimizer/tests/ExecutionGeneratorTestRunner.hpp, query_optimizer/tests/OptimizerTest.cpp, query_optimizer/tests/OptimizerTextTestRunner.cpp
Assigned to @jianqiao. Thanks!
The main goal of this PR is to construct multiple generators in `query_optimizer` once for all queries, as well as to do some clean ups in `query_optimizer`.
=> Refactor Generators in Optimizer

query_execution/QueryExecutionState.hpp
Assigned to @hbdeshmukh. Thanks.
This PR wraps the rebuild status into a dedicate struct. It also allows future extension info for the distributed versions.
=> Refactored RebuildStatus.

parser/preprocessed/SqlParser_gen.cpp, parser/preprocessed/SqlParser_gen.hpp
The preprocessed files were not checked in after the changes to datetime types in #97.
Thanks @zuyu for pointing it out.
=> Checking in preprocessed files for datetime change.

cli/CommandExecutor.cpp
This is a light-weight PR that enables the `\analyze` command to be followed by an arbitrary number of table names as arguments. E.g.
```
-- analyze tables A and B
\analyze A B
-- analyze all the tables in the database
\analyze
```
=> Enable \analyze command to be applied to specific tables

storage/FastSeparateChainingHashTable.hpp
- In resize, all the values are moved from original hash table are
copied to the new hash table using memcpy().
- Removed the for loop where values are constructed using 'new' operator, as
all the values are trivially constructible in the specialized
aggregation hash table implementation.
=> Remove unnecessary code from FastSeparateChainingHashTable::resize()

relational_operators/WorkOrderFactory.cpp
This PR fixed a minor bug introduced in #122 for some distributed execution engine unit tests, which are not covered by the existing CI.
=> Fixed the LIP bug in the distributed execution engine unit tests.

storage/SMAIndexSubBlock.cpp
On re-running SSB100, I found that we now have a situation where filters are used against SMAs. This is actually very easy to handle: either return the filter, or don't return the filter if your selectivity is ALL/NONE.
@hbdeshmukh I will update the SSB numbers for SMA here when this has finished compiling/running.
=> Allows filters to be evaluated in SMA

cli/CommandExecutor.cpp, cli/QuickstepCli.cpp, query_optimizer/CMakeLists.txt, query_optimizer/QueryProcessor.hpp
This small PR removed the `StorageManager` dependency in `QueryProcessor`.
=> Removed StorageManager from QueryProcessor.

query_execution/CMakeLists.txt, query_execution/ForemanBase.hpp, query_execution/ForemanDistributed.cpp, query_execution/ForemanDistributed.hpp, query_execution/ForemanSingleNode.cpp, query_execution/ForemanSingleNode.hpp, query_execution/PolicyEnforcerBase.hpp
This PR allows both `Foreman` implementations would do profiling.
=> Refactored printWorkOrderProfilingResults in Foreman.

cli/QuickstepCli.cpp, query_execution/CMakeLists.txt, query_execution/ForemanDistributed.cpp, query_execution/ForemanDistributed.hpp, query_execution/ForemanSingleNode.cpp, query_execution/ForemanSingleNode.hpp, query_execution/PolicyEnforcerBase.cpp, query_execution/PolicyEnforcerBase.hpp, query_execution/PolicyEnforcerDistributed.hpp, query_execution/PolicyEnforcerSingleNode.hpp
This PR simplifies the way to assign the enable_profile flag.
=> Refactor regarding the profile flag.

CMakeLists.txt, cli/CMakeLists.txt, cli/Flags.cpp, cli/Flags.hpp, cli/QuickstepCli.cpp
This small PR moves into a new file a CLI flag which will be also used by the distributed CLI.
=> Moved a CLI flag into a new file.

parser/ParsePartitionClause.hpp, parser/SqlParser.ypp, parser/preprocessed/SqlLexer_gen.cpp, parser/preprocessed/SqlLexer_gen.hpp, parser/preprocessed/SqlParser_gen.cpp, parser/preprocessed/SqlParser_gen.hpp, parser/tests/Create.test
This small PR changed `partition_type` in `parser` to `hash` or `range` from `0` or `1`.
=> Refactored partition_type in parser.

relational_operators/AggregationOperator.hpp, relational_operators/BuildHashOperator.hpp, relational_operators/HashJoinOperator.hpp, relational_operators/SelectOperator.hpp, storage/AggregationOperationState.hpp
=> Marked LIP as a non-default argument.

relational_operators/CMakeLists.txt, relational_operators/tests/HashJoinOperator_unittest.cpp
Added the unit test for PR #165.
=> Added test for Partitioned Hash Join.

BUILDING.md, README.md, third_party/README.md
- Updated master README file.
- Updated BUILDING instruction file.
- Updated description of the third party directory.
=> Documentation update after third party related changes

query_optimizer/ExecutionGenerator.cpp, relational_operators/SelectOperator.cpp, relational_operators/SelectOperator.hpp
Assigned to either @hbdeshmukh or @jianqiao.
This small PR simplified `SelectOperator` w/ partitions, so that w/o partitions is treated as a special case of that w/ a single partition.
=> Simplified the SelectOperator w/ partitions.

query_execution/CMakeLists.txt, query_execution/PolicyEnforcerBase.cpp, query_execution/PolicyEnforcerBase.hpp, query_execution/PolicyEnforcerDistributed.cpp, query_execution/QueryManagerBase.cpp, query_execution/QueryManagerBase.hpp, query_optimizer/QueryHandle.hpp
In the future, we may merge this PR and the similar code in `cli/QuickstepCli.cpp` into `PolicyEnforcerBase::onQueryCompletion`.
=> Visualized Execution DAG in the distributed version.

storage/AggregationOperationState.cpp, storage/AggregationOperationState.hpp, storage/CMakeLists.txt, storage/PackedPayloadHashTable.cpp, storage/PackedPayloadHashTable.hpp, utility/TemplateUtil.hpp
This PR uses the partitioned aggregation routine for parallelizing DISTINCT aggregation. It improves the performance of TPC-H Q16 from ~10s to ~2s with scale factor 100 on CloudLab machine.
=> Use partitioned aggregation for single-function DISTINCT aggregation.

cli/distributed/Executor.cpp, cli/distributed/Executor.hpp, query_execution/Shiftboss.cpp, query_execution/Shiftboss.hpp, query_optimizer/tests/DistributedExecutionGeneratorTestRunner.cpp, query_optimizer/tests/DistributedExecutionGeneratorTestRunner.hpp
- Global TMB between Foreman and Shiftboss.
- Local TMB between Workers and Shiftboss.
=> Used two TMB implementations in Shiftboss.

relational_operators/BuildAggregationExistenceMapOperator.cpp, relational_operators/BuildAggregationExistenceMapOperator.hpp, relational_operators/WorkOrderFactory.cpp
This PR addresses the bugs as pointed out in #185 as well as a few style issues.
=> Fix the problem in the "Fuse Aggregate with HashLeftOuterJoin" PR.

.gitattributes, release/.gitignore, release/README.md, release/release_cmds.sh, release/release_manager.profile
Includes:
- command to create artifacts
- command to publish release candidates
- command to test a release candidate
All commands are parameterized by the .profile file
@hakanmemisoglu is it perfect?
=> Init release scripts

query_execution/PolicyEnforcerDistributed.cpp
This is going to fix a whitespace issue which is causing travis to fail. I will merge this before creating RC6.
=> fixes travis ws issue

query_execution/PolicyEnforcerDistributed.cpp, release/Dockerfile, release/README.md
Many people have asked for the dockerfile I've been using to test the release. In light of this, I'll add it to the main repo.
I updated the documentation to give a quick example of usage.
=> Added dockerfile for release testing

.travis.yml, DEV_README.md, HISTORY.md, NOTICE, README.md, third_party/download_and_patch_prerequisites.sh, third_party/reset_third_party_dir.sh, third_party/src/tmb/README.md
- Changes to the various markup files.
- Added a new HISTORY file to track release information.
- Link update to apache in README files.
=> Added header to scripts and yaml files, updated NOTICE

release/.gitignore, release/release_cmds.sh
@hbdeshmukh Take a look, this will be useful in the future.
=> Added script for release license audit

utility/ExecutionDAGVisualizer.cpp
- Added number of work orders executed per operator.
- Added mean execution time per work order for each operator.
Notice the last two lines in each operator's entry.
=> QUICKSTEP-80 Enhanced the execution DAG visualization

storage/AggregationOperationState.cpp, storage/PartitionedHashTablePool.hpp
- Some NULL checks added without which we may have segmentation faults.
=> Bug fix in memory measurement

query_optimizer/CMakeLists.txt, query_optimizer/ExecutionGenerator.cpp, query_optimizer/ExecutionGenerator.hpp, query_optimizer/cost_model/CMakeLists.txt, query_optimizer/cost_model/SimpleCostModel.cpp, query_optimizer/cost_model/SimpleCostModel.hpp, query_optimizer/cost_model/StarSchemaSimpleCostModel.cpp, query_optimizer/cost_model/StarSchemaSimpleCostModel.hpp, query_optimizer/physical/CMakeLists.txt, query_optimizer/physical/PhysicalType.hpp, query_optimizer/physical/UnionAll.hpp, query_optimizer/resolver/Resolver.cpp, query_optimizer/strategy/CMakeLists.txt, query_optimizer/strategy/Join.cpp, query_optimizer/strategy/OneToOne.cpp, query_optimizer/tests/execution_generator/Select.test, query_optimizer/tests/physical_generator/Select.test, query_optimizer/tests/resolver/CMakeLists.txt, query_optimizer/tests/resolver/SetOperation.test, relational_operators/CMakeLists.txt, relational_operators/RelationalOperator.hpp, relational_operators/UnionAllOperator.cpp, relational_operators/UnionAllOperator.hpp
This PR implements the logical and physical layers to support UNION and INTERSECT operations, and also creates a new UnionAllOperator to do UnionAll operation.
=> Implement optimizer and execution layers for UNION and INTERSECT.

utility/DAG.hpp, utility/tests/DAG_unittest.cpp
- Implemented a very simple Kahn's algorithm for topological sorting of nodes
in the DAG class.
=> QUICKSTEP-88 Topological sort functionality in DAG

relational_operators/CMakeLists.txt, relational_operators/UnionAllOperator.cpp, relational_operators/UnionAllOperator.hpp, relational_operators/WorkOrder.proto, relational_operators/WorkOrderFactory.cpp
This PR implements protobuf for Union All operator in distributed setting.
=> Add protobuf support for UNION ALL operator.

relational_operators/WorkOrder.proto
This small PR sorts the `WorkOrder` in the alphabet order.
=> WorkOrder proto clean-up.

expressions/predicate/Predicate.hpp, expressions/scalar/Scalar.cpp, expressions/scalar/Scalar.hpp, expressions/scalar/ScalarSharedExpression.cpp, expressions/scalar/ScalarSharedExpression.hpp, expressions/scalar/tests/ScalarCaseExpression_unittest.cpp, query_optimizer/expressions/CommonSubexpression.hpp, query_optimizer/expressions/SimpleCase.cpp, query_optimizer/rules/CollapseSelection.cpp, query_optimizer/rules/CollapseSelection.hpp, query_optimizer/rules/ExtractCommonSubexpression.cpp, query_optimizer/rules/ExtractCommonSubexpression.hpp, query_optimizer/rules/ReuseAggregateExpressions.cpp, query_optimizer/rules/ReuseAggregateExpressions.hpp
This PR fixes the issues in #237.
=> Fix the issues with the common subexpression feature.

query_optimizer/ExecutionGenerator.cpp
If the output relation for CopyFrom has partition info, honor that for all new tuples.
=> Partition-aware CopyFrom.

storage/SplitRowStoreTupleStorageSubBlock.cpp, storage/SplitRowStoreTupleStorageSubBlock.hpp, storage/tests/SplitRowStoreTupleStorageSubBlock_unittest.cpp
This PR adjusts the implementation of `CopyGroupList::merge_contiguous()` to handle some cases correctly.
E.g. let `R`be a split-row-store relation with integer attributes `x`,`y`,`z`. It is expected that for query
```
SELECT x, y, z
FROM R;
```
`merge_contiguous()` merges all attributes into one `ContiguousAttrs` copy group, with `bytes_to_copy` set to 12 (size of three integers).
It is also expected that for query
```
SELECT x, y, y
FROM R;
```
`merge_contiguous()` merges all attributes into two `ContiguousAttrs` copy groups, one for `x, y` and one for the last `y`.
=> Fix a problem in CopyGroupList + minor style fixes

query_optimizer/rules/PushDownLowCostDisjunctivePredicate.cpp
This PR improves the `PushDownLowCostDisjunctivePredicate` optimization to consider more applicable scenarios -- precisely it will push down the partial predicate when it has a low selectivity. This results in 4X speedup for TPC-H Q19.
=> Improve disjunctive predicate pushdown to optimize more scenarios

query_execution/PolicyEnforcerDistributed.cpp, query_execution/QueryManagerDistributed.cpp, query_execution/QueryManagerDistributed.hpp
This PR includes minor code improvements for the scheduler in the distributed version.
=> Minor refactor scheduler in the distributed version.

relational_operators/WorkOrderFactory.cpp
=> Minor refactors in WorkOrderFactory.

query_execution/ForemanDistributed.cpp, query_execution/PolicyEnforcerDistributed.cpp, query_execution/PolicyEnforcerDistributed.hpp, query_execution/QueryContext.proto, query_execution/QueryManagerDistributed.cpp, query_execution/QueryManagerDistributed.hpp, query_optimizer/ExecutionGenerator.cpp, relational_operators/CMakeLists.txt, relational_operators/NestedLoopsJoinOperator.cpp, relational_operators/NestedLoopsJoinOperator.hpp, relational_operators/WorkOrder.proto
This PR allows nlj to accept partitioned inputs, and a later PR will add the optimizer support.
=> Added operator and execution support for partitioned nested loops join.

storage/InsertDestination.cpp, storage/InsertDestination.hpp
This small refactor improves the performance of the functions.
=> Refactored PartitionAwareInsertDestination::getPartitionId.

query_optimizer/rules/PushDownLowCostDisjunctivePredicate.cpp
This small PR fixed the bug in PR #174 that we may have two identical `Selection`s due to the predicate pushdown. The fix avoids such case by skipping the pushdown if and only if a node's input is a base table.
Note that, the fix only works for an `Aggregate` and a `Selection`, but skipped any `BinaryJoin`, which requires checking both `left` and `right`, and what attributes the disjunctive predicate are referencing from.
For the following test query in `Partition.test`:
```
SELECT fact.id, test.char_col
FROM test JOIN fact ON test.int_col = fact.id
WHERE test.int_col > 0 OR test.int_col < 0;
```
Previously to this PR, we would generate a bad plan with two same `Selection`s.
```
9: I0708 15:31:29.931959 3661849536 PhysicalGenerator.cpp:192] After applying rule …
```
=> Skip predicate pushdown if the node's input is a base relation.

query_optimizer/rules/CMakeLists.txt, query_optimizer/rules/CollapseSelection.cpp, query_optimizer/tests/physical_generator/Select.test
This small PR improves the `CollapseSelection` rule for selections with predicates.
=> Collapse Selections with predicates.

query_optimizer/CMakeLists.txt, query_optimizer/ExecutionGenerator.cpp, relational_operators/InitializeAggregationOperator.cpp, relational_operators/InitializeAggregationOperator.hpp, storage/AggregationOperationState.cpp, storage/AggregationOperationState.hpp, storage/AggregationOperationState.proto, storage/CMakeLists.txt, storage/CollisionFreeVectorTable.cpp, storage/CollisionFreeVectorTable.hpp, storage/HashTable.proto, storage/HashTableFactory.hpp, storage/StorageConstants.hpp
=> Determine #InitPartitions for CollisionFreeVectorTable in the optimizer.

.travis.yml
Disable NetworkUtil_unittest in Travis.
=> Disabled NetworkUtil_unittest.

query_execution/QueryExecutionState.hpp, query_execution/QueryManagerBase.cpp, query_execution/QueryManagerSingleNode.cpp, query_execution/QueryManagerSingleNode.hpp
This PR made minor improvements in the query execution engine.
=> Minor changes in QueryManager and QueryExecutionState.

cli/QuickstepCli.cpp, relational_operators/NestedLoopsJoinOperator.hpp, relational_operators/RelationalOperator.hpp, relational_operators/SortRunGenerationOperator.hpp, utility/CMakeLists.txt, utility/ExecutionDAGVisualizer.cpp
This PR improved `ExecutionDAGVisualizer` by adding more operator supports, displaying the partition info, as well as some minor refactors.
=> QUICKSTEP-92: Improved ExecutionDAGVisualizer.

query_optimizer/rules/CMakeLists.txt, query_optimizer/rules/Partition.cpp
This PR deals with `Sort` w/ partitioned inputs.
=> Added Partition rules for Sort.

transaction/LockManager.cpp
- Added a false condition for acquiring lock
- Added clarifying comment.
=> Bug fix in LockManager loop

catalog/PartitionSchemeHeader.hpp
This small PR optimized out the mod operation `%` when possible.
=> Optimized the mod operation in HashPartition.

storage/SplitRowStoreTupleStorageSubBlock.cpp
=> Removed the virtual function call in InvokeOnAnyValueAccessor.

relational_operators/tests/HashJoinOperator_unittest.cpp, storage/InsertDestination.cpp, storage/InsertDestination.hpp
The method is used only for testing.
=> Moved InsertDestination::getTouchedBlocks as a private method.

expressions/scalar/ScalarCaseExpression.cpp, relational_operators/HashJoinOperator.cpp, storage/AggregationOperationState.cpp, storage/BloomFilterIndexSubBlock.cpp, storage/CMakeLists.txt, storage/CSBTreeIndexSubBlock.cpp, storage/CompressedColumnStoreTupleStorageSubBlock.cpp, storage/CompressedPackedRowStoreTupleStorageSubBlock.cpp, storage/InsertDestination.hpp, storage/SMAIndexSubBlock.cpp, storage/StorageBlock.cpp, storage/TupleIdSequence.hpp, storage/TupleStorageSubBlock.cpp, utility/BitVector.hpp, utility/lip_filter/LIPFilterAdaptiveProber.hpp, utility/tests/BitVector_unittest.cpp
This PR added a new `set` API for `TupleIdSequence`, and has some performance improvement.
=> Added a new set API for TupleIdSequence.

parser/CMakeLists.txt, parser/ParseBlockProperties.hpp, parser/tests/Create.test, query_optimizer/OptimizerTree.hpp, query_optimizer/resolver/Resolver.cpp, query_optimizer/tests/resolver/Create.test
This small PR allows to create a relation w/ column store, while not specifying a sort attribute.
=> Relax the sort requirement in columnstore.

CMakeLists.txt, types/TypedValue.hpp
No relative path allowed in the include path.
=> Fixed the include path for farmhash.

storage/SeparateChainingHashTable.hpp
This PR fixes the problem that Quickstep hangs when resizing `SeparateChainingHashTable` during the execution of `BuildHashOperator`.
Here is a sequence of queries that reproduce the problem:
```
CREATE TABLE r(x INT, y INT);
CREATE TABLE s(x INT, y INT);
CREATE TABLE t(x INT, y INT);
INSERT INTO r SELECT 1, 1 FROM generate_series(1, 200) AS g(x);
INSERT INTO s SELECT 1, 1 FROM generate_series(1, 200) AS g(x);
INSERT INTO t SELECT 1, 1 FROM generate_series(1, 1000) AS g(x);
\analyze
SELECT COUNT(*) FROM r, s, t WHERE r.x = s.x AND r.y = s.y AND s.x = t.x AND s.y = t.y;
```
The problem is caused by the [`resize()` call](https://github.com/apache/incubator-quickstep/blob/master/storage/HashTable.hpp#L1514) in `HashTable::putValueAccessorCompositeKey()` when `using_prealloc` is true. In this …
=> Fix SeparateChainingHashTable::resize()

CMakeLists.txt, cli/DefaultsConfigurator.cpp, cli/DefaultsConfigurator.hpp, cli/distributed/CMakeLists.txt, cli/distributed/Cli.cpp, cli/distributed/Executor.cpp
@yuanchenl Please test this PR using Docker. Thanks!
=> Fixed the bug that Executor / Cli does not create directory for StorageManager.

CMakeLists.txt
Upgrading CMake, as is required by glog which is a third party dependency (discussed in #327).
=> Upgrade cmake version.

query_optimizer/rules/StarSchemaHashJoinOrderOptimization.cpp, query_optimizer/rules/StarSchemaHashJoinOrderOptimization.hpp
This PR fixed the bug in join reordering due to the pointer address-based comparison. It also added a new rule that prefers the build side which does not produce output, and did minor refactors for the file.
=> QUICKSTEP-125: Fixed the non-determinism in JoinReordering.

cli/tests/CMakeLists.txt, cli/tests/CommandExecutorTestRunner.cpp, cli/tests/DistributedCommandExecutorTest.cpp, cli/tests/DistributedCommandExecutorTestRunner.cpp, cli/tests/DistributedCommandExecutorTestRunner.hpp, cli/tests/command_executor/CMakeLists.txt, cli/tests/command_executor/D.test, cli/tests/command_executor/Dt.test
This PR fixed the command execution bugs in the distributed version, and now it is consistent with the single-node version.
=> Fixed the command execution bug in the distributed version.

CMakeLists.txt, query_execution/QueryExecutionTypedefs.hpp, storage/BlockWire.proto, storage/CMakeLists.txt, storage/DataProviderThread.cpp, storage/DataProviderThread.hpp, storage/StorageManager.cpp, storage/StorageManager.hpp, storage/tests/DataProviderThread_unittest.cpp
- Thread used for receiving block requests from clients and sending the
contents of a block back to the client.
=> QUICKSTEP-127 Data provider thread 

autofix_cmakelists.py, query_optimizer/tests/execution_generator/Join.test, relational_operators/HashJoinOperator.cpp, storage/CMakeLists.txt
This PR fixes a bug in `HashJoinOperator` w.r.t. the swapping of probe/build sides in a previous PR.
=> Fix a bug in HashJoinOperator

third_party/src/tmb/benchmarks/CMakeLists.txt, third_party/src/tmb/benchmarks/src/bus_setup.cc
This minor PR fixed some build issues related to the tmb benchmark directory.
=> Fixed the build issues regarding tmb benchmark.
