.travis.yml
storage/SimpleScalarSeparateChainingHashTable.hpp

- Earlier check for isFull() was that whether there is at least one empty bucket available for insertion.
- Now isFull() can check if there is enough space for adding specified number of buckets.
- To reproduce the bug behind this fix: Run TPC-H Q2 on SF100 dataset after
running the \analyze command. The optimizer allocates smaller than
necessary space for one of the hash joins. The resize() is triggered
but never gets executed because of the restrictive isFull() condition.

Bug fixed in SimpleScalarSeparateChainingHashTable::isFull()

---

expressions/CMakeLists.txt
expressions/aggregation/CMakeLists.txt

Both the CMakeLists files in this PR refer to libraries that don't exist. expressions/CMakeLists refers to a library that has probably been renamed. For the other file, I can't find any *_AggregationHandleUtil library. Not sure why it's been working so far!

Fix typos in CMakeLists.txt.

---

.travis.yml

This PR applies the fix from @pateljm's PR #9, with some other typos and fixes. 
For Clang, build and tests succeed on Travis. 
For GCC, there are OOM errors (unrelated to the present change).

Fix to clang problems in Travis

---

storage/CompressedBlockBuilder.cpp

This PR fixes a potential bug in `CompressedBlockBuilder`. This fix is necessary for a subsequent PR on `TextScanOperator` where each work order first constructs a `ColumnVectorsValueAccessor` and then bulk insert the value accessor into a `CompressedColumnStoreTupleStorageSubBlock`.
In the typical scenario, `CompressedBlockBuilder` first collects tuples from a `ValueAccesor` into a `PtrVector<Tuple>` , then calls `buildDictionary` to process the tuples. However, the collected tuples would not own the underlying attribute values' **`out_of_line_data`** if the value is of `Char` or `VarChar` type. This incurs segmentation fault if the `ValueAccessor` (which owns the `out_of_line_data`) gets released before `buildDictionary` is completed.
The fix is just to ensure that the …

Fix a potential segfault in CompressedBlockBuilder

---

.travis.yml
CMakeLists.txt
cli/CMakeLists.txt
query_execution/CMakeLists.txt
query_optimizer/CMakeLists.txt
query_optimizer/tests/CMakeLists.txt
relational_operators/CMakeLists.txt
storage/CMakeLists.txt
transaction/CMakeLists.txt

Modify the build process to allow optional use of shared libraries instead of the static libraries we use today. The benefits are 
- much smaller build directory size (I’m seeing < 5GB for release mode, as opposed to the usual 40GB with static libs)
- slightly faster build time (went from 18-20min to 14-15min on the CloudLab machine with 40 jobs)
- reduced memory consumption (average memory consumption during build went from 12GB to 8.5GB)
To use this, just turn on the CMake flag BUILD_SHARED_LIBS. Currently, we don't support the use of both shared and static libraries in the build, because that leads to some really nasty bugs with the common third party libraries (GFlags, GLog, ProtoBuf) due to double-linking. 
All tests passed locally (both with the flag turned on and off). 
Also, see …

Add option to build using shared libraries.

---

.travis.yml

[Identical to #21, but that got messed up due to some git foo.]
This change should reduce memory consumption and build time.
Comparing Travis run times for PR #21  (https://travis-ci.org/apache/incubator-quickstep/builds/136474629) with one from earlier today (https://travis-ci.org/apache/incubator-quickstep/builds/136370961), almost all the run times have gone down to a certain extent. It's particularly helpful for the GCC runs with copy elision (>10% speedup).

Use shared libraries when building on Travis

---

build/profile_build.sh

I introduced a bug during one of the many merges!

Fix bug: specify log file name correctly

---

parser/CMakeLists.txt

set_target_properties() overwrites per-target COMPILE_FLAGS rather than replacing them. Also, compiler flags should be checked before enabling them.

Fix conditional per-target flags for lexer

---

cli/CommandExecutor.cpp
cli/QuickstepCli.cpp
query_execution/QueryExecutionUtil.hpp
query_optimizer/tests/ExecutionGeneratorTestRunner.cpp
query_optimizer/tests/ExecutionGeneratorTestRunner.hpp

The ``\analyze`` command issues SQL queries. Due to a recent change in the execution engine (PR #14), there was a bug in issuing the queries, which is fixed in this branch. The issue is described below:
The workflow to issue queries is as follows:
1. Create a TMB message consisting of the query. 
2. Send the TMB message from main thread to the Foreman thread.
3. Foreman executes the query.
4. Foreman sends a completion message back to the main thread.
5. Main thread receives the completion message and proceeds. 
In the relevant function where ``\analyze`` queries are issued, we were not capturing the response in step 5, which gave a segmentation fault sometimes. 
This branch also puts a common code to receive feedback from Foreman upon query completion in a function, which gets used in …

Bug fixed in \analyze command and reuse code.

---

query_execution/PolicyEnforcer.cpp
query_execution/QueryExecutionMessages.proto
query_execution/QueryManager.cpp
query_execution/Worker.cpp
query_execution/Worker.hpp
query_execution/tests/QueryManager_unittest.cpp

This PR includes the following changes: 
- Measure work order execution time
- Split the WorkOrderCompletion proto message in two: Normal and Rebuild work orders.
- Add execution time field in the both types of WorkOrderComplete proto messages.
- Include the recorded time in both kind of WorkOrderComplete proto messages that are sent back to Foreman.
Also note that, the CPU overhead for measuring this time is pretty low. In terms of memory, we pay a cost of an additional 8 bytes in each completion message sent from each worker to the Foreman. 
This feature can be quite helpful for performance monitoring. We can take a look at individual work order execution time of different operators. I am planning to create another PR which can produce reports consisting of average/max/min/variance of …

QUICKSTEP-21 Measure execution time of WorkOrders

---

parser/CMakeLists.txt
storage/BasicColumnStoreTupleStorageSubBlock.cpp
storage/BasicColumnStoreTupleStorageSubBlock.hpp
storage/StorageBlockLayout.proto
storage/tests/BasicColumnStoreTupleStorageSubBlock_unittest.cpp

This makes sorting an optional (instead of required) property of BasicColumnStoreTupleStorageSubBlock.

QUICKSTEP-18: Allow BasicColumnStoreTupleStorageSubBlock to be unsorted

---

cli/QuickstepCli.cpp
query_execution/CMakeLists.txt
query_execution/Foreman.cpp
query_execution/Foreman.hpp
query_execution/PolicyEnforcer.cpp
query_execution/PolicyEnforcer.hpp

This PR provides an initial version of the support required to report individual work order execution performance. Some highlights are described below: 
- A flag to enable work order profiling report generation.
- At the end of each query, a report is generated which includes worker
ID, its NUMA socket, the query ID, the operator that produced the WorkOrder and the
execution time in microseconds.
- The output is printed on stdout in CSV format as of now.
As this is a rudimentary support for the functionality, there is a lot of future work in this regards, which includes printing of CPU core information, printing operator name, allowing user to specify a file where the output can be written, extend the support for rebuild WorkOrder statistics etc.
Edit: Added query ID.

QUICKSTEP-24 Report generation support for work order execution statistics

---

query_optimizer/expressions/CMakeLists.txt
query_optimizer/expressions/ExpressionType.hpp
query_optimizer/expressions/PatternMatcher.hpp
query_optimizer/expressions/WindowAggregateFunction.cpp
query_optimizer/expressions/WindowAggregateFunction.hpp
query_optimizer/logical/CMakeLists.txt
query_optimizer/logical/LogicalType.hpp
query_optimizer/logical/PatternMatcher.hpp
query_optimizer/logical/WindowAggregate.cpp
query_optimizer/logical/WindowAggregate.hpp
query_optimizer/resolver/CMakeLists.txt
query_optimizer/resolver/Resolver.cpp
query_optimizer/resolver/Resolver.hpp
query_optimizer/strategy/CMakeLists.txt
query_optimizer/strategy/OneToOne.cpp
query_optimizer/tests/logical_generator/Select.test
query_optimizer/tests/resolver/Select.test

Now the resolver could form a logical plan for window aggregate function based on the parsed result.
Suppose we have the following query:
SELECT attr0, avg(attr1) OVER
(PARTITION BY attr2
ORDER BY attr3
ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING)
FROM table1;
The logical plan will look like this:
input_table -> sort on (attr2, attr3) -> window aggregate -> project on (attr0, avg(attr1)).
Two new classes are introduced: quickstep::optimizer::expressions::WindowAggregateFunction and quickstep::optimizer::logical::WindowAggregate:
-WindowAggregateFunction will keep the function information and window information. 
-WindowAggregate will store the input logical node and an alias wrapper of WindowAggregateFunction.
In current version, we only support one window aggregate function. When the …

QUICKSTEP-20: Resolver support for Window Aggregate Function

---

.travis.yml

LLVM Apt repositories are back online. 
http://lists.llvm.org/pipermail/llvm-dev/2016-June/101500.html

Go back to using LLVM Apt repositories

---

cli/QuickstepCli.cpp

- Fixed a bug thereby Quickstep command line now handles negative
number of worker threads correctly.
- If the user provides zero or fewer worker threads, we switch to the
default number of worker threads, instead of terminating the process.

Handle negative number of worker threads as input

---

query_execution/Foreman.cpp

- Now prints query ID along with each work order entry.
- Removed spaces between two columns.

Minor changes in profiling work order output.

---

CMakeLists.txt
cli/CMakeLists.txt
cli/CommandExecutor.cpp
cli/CommandExecutor.hpp
cli/QuickstepCli.cpp
cli/tests/CMakeLists.txt
cli/tests/CommandExecutorTestRunner.cpp
cli/tests/CommandExecutorTestRunner.hpp
query_execution/CMakeLists.txt
query_execution/ForemanBase.hpp
query_execution/ForemanSingleNode.cpp
query_execution/ForemanSingleNode.hpp
query_optimizer/tests/CMakeLists.txt
query_optimizer/tests/ExecutionGeneratorTestRunner.cpp
query_optimizer/tests/ExecutionGeneratorTestRunner.hpp

Renamed `ForemanBase` and `ForemanSingleNode` from `ForemanLite` and `Foreman`, respectively.

Renamed Foreman related classes.

---

query_execution/QueryManagerBase.cpp

Modified the order in which we check the completion of query and completion of an operator in the queryStatus function. Based on the semantics of the return value of ``queryStatus`` function, query completion return code takes precedence over operator completion. Hence changed the order in which we perform these checks. Note that this bug was present in the original code and was carried forward during the code refactoring of QueryManager.

Minor bug fix in QueryManager base.

---

query_execution/QueryExecutionMessages.proto
query_execution/QueryExecutionTypedefs.hpp
query_execution/Shiftboss.cpp
query_execution/Shiftboss.hpp

Used by the distributed version only.

Renamed a QueryExecutionMessage.

---

query_execution/ForemanSingleNode.cpp
query_execution/QueryExecutionMessages.proto
query_execution/QueryExecutionUtil.hpp
query_execution/README.md
query_execution/WorkerMessage.hpp
query_execution/tests/BlockLocator_unittest.cpp
storage/tests/DataExchange_unittest.cpp
third_party/tmb/include/tmb/tagged_message.h

This constructor avoids creating [a dummy payload](https://github.com/apache/incubator-quickstep/blob/master/query_execution/ForemanSingleNode.cpp#L171).

TMB: Added Support for an Empty, but Typed TaggedMessage.

---

query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
query_optimizer/PhysicalGenerator.cpp
query_optimizer/physical/HashJoin.hpp
query_optimizer/rules/BottomUpRule.hpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/SwapProbeBuild.cpp
query_optimizer/rules/SwapProbeBuild.hpp
query_optimizer/tests/physical_generator/Select.test

Improvement for QUICKSTEP-37. ([https://issues.apache.org/jira/browse/QUICKSTEP-37]())

Move hash join's probe and build node decision from ExecutionGenerator to PhysicalOptimizer

---

cyclic_dependency.py
query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
query_optimizer/PhysicalGenerator.cpp
query_optimizer/physical/HashJoin.hpp
query_optimizer/rules/BottomUpRule.hpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/SwapProbeBuild.cpp
query_optimizer/rules/SwapProbeBuild.hpp
query_optimizer/tests/physical_generator/Select.test
validate_cmakelists.py

Three core changes:
- update from python2 print command, to python3 print function [1]
- switch from xrange to range [1]
- switch from dict.iteritems to iter(dict.items())  [2]
[1] http://python-future.org/compatible_idioms.html
[2] http://legacy.python.org/dev/peps/pep-0469/

QUICKSTEP-38. Add support for python3 to utility scripts

---

cli/CommandExecutor.cpp
cli/QuickstepCli.cpp
cli/tests/CommandExecutorTestRunner.cpp
query_execution/tests/QueryManagerSingleNode_unittest.cpp
query_optimizer/CMakeLists.txt
query_optimizer/QueryHandle.hpp
query_optimizer/QueryProcessor.cpp
query_optimizer/QueryProcessor.hpp
query_optimizer/tests/ExecutionGeneratorTestRunner.cpp

W/ the concurrent query support, `QueryHandle` needs to capture the TMB client id of the `CLI` which submits the query, so `Foreman` could later reply the query result to the right `CLI`.

Added TMB Client Id in QueryHandle.

---

query_execution/CMakeLists.txt
query_execution/PolicyEnforcerBase.cpp
query_execution/PolicyEnforcerBase.hpp
query_execution/PolicyEnforcerDistributed.cpp
query_execution/PolicyEnforcerDistributed.hpp
query_execution/QueryExecutionMessages.proto
query_execution/QueryExecutionTypedefs.hpp
query_execution/QueryManagerBase.cpp
query_execution/QueryManagerBase.hpp
query_execution/Shiftboss.cpp
query_execution/Shiftboss.hpp
storage/CMakeLists.txt

Background: We use mmap to allocate memory whenever it is available. There is a check in storage module's CMakeLists to further check if mmap can support HugePage allocation. 
Issue: The check for HugePage allocation used the definition for ``GNU_SOURCE`` macro. Some compilers by default have this macro defined, which causes the compiler to throw a warning "macro already defined". As warnings are treated as errors, this check fails, therefore CMake declares that HugePage support is not available. 
Fix: Guard the definition by #ifndef directive.

Added guards for gnu_source definition in storage CMakeLists

---

relational_operators/HashJoinOperator.cpp
relational_operators/WorkOrderFactory.cpp

This PR fixed two bugs:
1. Missed required `query_id` in `HashJoinWorkOrder`.
2. The incorrect sanity check for join attribute ids in `HashJoinWorkOrder`.

Fixed bugs in creating HashJoinWorkOrderProtos.

---

query_execution/QueryContext.hpp
query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
relational_operators/CMakeLists.txt
relational_operators/DestroyAggregationStateOperator.cpp
relational_operators/DestroyAggregationStateOperator.hpp
relational_operators/FinalizeAggregationOperator.hpp
relational_operators/WorkOrder.proto
relational_operators/WorkOrderFactory.cpp
relational_operators/tests/AggregationOperator_unittest.cpp

- Similar to the DestroyHash operator, this operator destroys the AggregationState once the Finalize aggregation operator finishes its execution.
- Optimizer support for DestroyAggregationState operator.

QUICKSTEP-43 Introduced DestroyAggregationState operator

---

relational_operators/CMakeLists.txt
relational_operators/RelationalOperatorsConfig.h.in
relational_operators/TextScanOperator.cpp

This PR fixes QUICKSTEP-36 
- Perform access check on a file before opening it to import a table.

QUICKSTEP-36 Quickstep gives segmentation fault when it imports table from a file that does not have access rights.

---

query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
query_optimizer/ExecutionGenerator.hpp
query_optimizer/cost_model/CMakeLists.txt
query_optimizer/cost_model/CostModel.hpp
query_optimizer/cost_model/StarSchemaSimpleCostModel.cpp
query_optimizer/cost_model/StarSchemaSimpleCostModel.hpp
query_optimizer/expressions/ExpressionUtil.hpp
query_optimizer/rules/StarSchemaHashJoinOrderOptimization.hpp

This PR revises `StarSchemaSimpleCostModel` to provide better group cardinality estimation for aggregations. This information will be used by a subsequent PR from Harshad to decide when to use _partitioned hash tables_.
The estimation relies on the _number of distinct values_ statistic of each group-by attribute, which can be gathered by running `\analyze` command on the corresponding tables.
This PR does not affect the query plans for SSB queries. It changes some of the TPC-H query plans (and a subsequent `LIPFilter` PR will bring more changes to TPC-H query plans).

Improve StarSchemaSimpleCostModel to provide better group cardinality estimation for aggregations.

---

query_execution/CMakeLists.txt
query_execution/QueryExecutionUtil.hpp

Minor fixes to the file `QueryExecutionUtil.hpp`, including `iwyu`.

IWYU fixes for QueryExecutionUtil.

---

storage/AggregationOperationState.cpp

Replace getHashTable() call with getHashTableFast() call.
Thanks @jianqiao for pointing out the bug.

Minor bug fix in AggregationOperationState

---

.travis.yml

This a one-line change PR that fixes Travis build job failures due to compiler out-of-memory errors by running a single thread while building a release version.

Update travis to run only single thread while building release version

---

query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
query_optimizer/ExecutionGenerator.hpp
query_optimizer/cost_model/CMakeLists.txt
query_optimizer/cost_model/SimpleCostModel.cpp
query_optimizer/cost_model/SimpleCostModel.hpp

This PR alleviates the issue that `JoinHashTable` size is under-estimated.

Use SimpleCostModel for estimating JoinHashTable size

---

expressions/aggregation/AggregationHandle.hpp
expressions/aggregation/AggregationHandleAvg.hpp
expressions/aggregation/AggregationHandleMax.hpp
expressions/aggregation/AggregationHandleMin.hpp
expressions/aggregation/AggregationHandleSum.hpp
query_execution/QueryContext.hpp
relational_operators/DestroyAggregationStateOperator.cpp
storage/AggregationOperationState.cpp
storage/AggregationOperationState.hpp
storage/CMakeLists.txt
storage/FastSeparateChainingHashTable.hpp
storage/HashTableBase.hpp

- Destruction of payload in hash table.
- Separate phases of payload destruction of aggregation hash tables.
- First the payloads will be destructed by respective aggregation
handles.
- Second the hash table itself will be destructed.
- Remove FastSeparateChaining::DestroyValues function.

Fix memory leak in FastSeparateChaining hash table

---

storage/FastSeparateChainingHashTable.hpp

- Change in pointer arithmetic now ensures that destroyPayload will be
called for correct payload entry in each bucket.
Thanks @jianqiao in fixing this bug.

Fix a bug in FastSeparateChainingHashTable::destroy payload

---

query_execution/ForemanDistributed.cpp
query_execution/ForemanDistributed.hpp
query_execution/PolicyEnforcerBase.cpp
query_execution/PolicyEnforcerBase.hpp
query_execution/PolicyEnforcerDistributed.cpp
query_execution/QueryExecutionMessages.proto
query_execution/QueryExecutionUtil.hpp
query_execution/Shiftboss.cpp
query_optimizer/tests/DistributedExecutionGeneratorTestRunner.hpp

Assigned to @hbdeshmukh. Thanks!
This PR initiates (and tears down) all `Shiftboss`es to execute an admitting query, although we limit to only use the single `Shiftboss` for now. The next step is to schedule `WorkOrder`s on any available `Shiftboss`es.
Note that the current implementation is not fault tolerant to `Shiftboss` failures, nor scale-up and down.

Initiated query execution data structure in all Shiftbosses.

---

storage/FastSeparateChainingHashTable.hpp

- Using handles_ vector directly in FastSeparateChainingHashTable can
cause problems. One example is a distinctify hash table which doesn't
accept any payload. In this case, the reference to handles_ vector
becomes garbage after the constructor gets executed. Therefore to
avoid faults about accessing an invalid reference, we use the number
of handles as a guarding mechanism.
- Verified by reducing the hash table size artificially, so as to forcing a ``resize()`` operation. The ``destroyPayload()`` function gets called in ``resize()``. The fix in this PR fixes the behavior of ``destroyPayload`` function.

Store handle count in FastSeparateChainingHashTable

---

expressions/scalar/ScalarAttribute.cpp
query_execution/QueryContext.hpp
query_optimizer/PhysicalGenerator.cpp
query_optimizer/rules/AttachLIPFilters.cpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/tests/OptimizerTextTest.cpp
relational_operators/AggregationOperator.cpp
relational_operators/AggregationOperator.hpp
relational_operators/BuildHashOperator.cpp
relational_operators/BuildHashOperator.hpp
relational_operators/CMakeLists.txt
relational_operators/HashJoinOperator.cpp
relational_operators/HashJoinOperator.hpp
relational_operators/SelectOperator.cpp
relational_operators/SelectOperator.hpp
relational_operators/WorkOrder.proto
relational_operators/WorkOrderFactory.cpp
storage/AggregationOperationState.cpp
storage/AggregationOperationState.hpp
storage/CMakeLists.txt
storage/StorageBlock.cpp
storage/StorageBlock.hpp
utility/PlanVisualizer.cpp
utility/lip_filter/CMakeLists.txt
utility/lip_filter/LIPFilterBuilder.hpp
utility/lip_filter/LIPFilterUtil.hpp

This PR follows #113 and #118 and adds backend support for LIPFilters.
- `BuildHashOperator` supports building of LIPFilters.
- `SelectOperator`, `HashJoinOperator` and `AggregateOperator` support probing of LIPFilters. 
For `SelectOperator` and `AggregateOperator`, if an filter predicate is present, then the LIPFilters will be applied AFTER the filter predicate.
The latest physical plans w/ LIPFilters for SSB/TPC-H SF100:
[SSB_physical_plans.pdf](https://github.com/apache/incubator-quickstep/files/547240/SSB_physical_plans.pdf)
[TPCH_physical_plans.pdf](https://github.com/apache/incubator-quickstep/files/547241/TPCH_physical_plans.pdf)
Here are performance results for SSB/TPC-H SF100.
<table>
<tr>
<td><b>SSB SF100</b></td>
<td><b>master (ms)</b></td>
<td><b>w/ LIPFilter (ms)</b></td> …

Add backend support for LIPFilters.

---

relational_operators/FinalizeAggregationOperator.cpp
relational_operators/FinalizeAggregationOperator.hpp
storage/AggregationOperationState.cpp
storage/AggregationOperationState.hpp
storage/CMakeLists.txt
storage/HashTablePool.hpp
storage/PartitionedHashTablePool.hpp
storage/StorageBlock.cpp
storage/StorageBlock.hpp
types/containers/CMakeLists.txt
types/containers/Tuple.hpp
utility/CMakeLists.txt
utility/CompositeHash.hpp

- Used for creating a pool of hash tables such that each hash table
belongs to a unique partition.
- The partitioning is done on the group-by keys.
- Wrote a utility function to compute composite hash of a group of
TypedValues.
- The Tuple class now supports a method to compute the hash of the entire
tuple (i.e. hash key is the composite key made up of all the
attributes in the tuple).
- Added a check for whether the aggregation is partitioned or not.
- The conditions for whether the aggregation can be partitioned
are as follows:
1. The query has a GROUP BY clause.
2. There are no aggrgeations with a DISTINCT clause.
3. The estimated number of groups are greater than a pre-defined
threshold.
4. The query has at least one aggregation function.
- Method for partitioned aggregation with …

QUICKSTEP-57 Support for performing partitioned aggregation.

---

storage/SplitRowStoreTupleStorageSubBlock.cpp
storage/tests/SplitRowStoreTupleStorageSubBlock_unittest.cpp

This change fixes an incorrect estimate for the maximum size of a tuple. Previously, it was not accounting for the space used by the fixed length portion of the tuple.
The unit tests were modified because, now, we insert fewer tuples. It's actually quite hard to test the correct number of tuples which will be inserted, so this has been left as a TODO. We were able to load all of the SSB tables correctly now.

QUICKSTEP-61 Fixes varlen insert bug.

---

query_optimizer/cost_model/CMakeLists.txt
query_optimizer/cost_model/SimpleCostModel.cpp

- Use exact CatalogRelation statistics in SimpleCostModel's
estimateCardinality method, whenever stats on that relation are available.
This feature particularly helps in TPC-H Q21 (100 scale factor), in which there are two large hash tables built on the lineitem (cardinality: 600M) table. Such large hash tables leave very little room in the buffer pool for other operators, causing evictions and resulting in a large execution time. 
In the original branch, the estimate for the number of entries in the hash table, as provided by the cost model is 1.09B. After this PR, we can reduce that estimate to 600M. Running Q21 the CloudLab machine, gave the following results: (time in milliseconds).
| Original | After changes | Speed-up |
|----------|---------------|----------|
| 178,787  | 12,043 …

Refine estimates for estimateCardinality for TableReference

---

query_optimizer/tests/CMakeLists.txt
query_optimizer/tests/DistributedExecutionGeneratorTestRunner.cpp
query_optimizer/tests/DistributedExecutionGeneratorTestRunner.hpp
query_optimizer/tests/TestDatabaseLoader.hpp
storage/DataExchangerAsync.cpp

Assigned to @hbdeshmukh. Thanks.
This goal of the distributed unit test is to simulate a distributed query execution engine that uses multiple separate execution sites (`Shiftboss`). In particular, this PR uses `BlockLocator` and `DataExchangerAsync`, to locate all the blocks, and fetch a remote block in an async manner, respectively.
In other words, this PR archives the goal above by enabling that `StorageManager` in `Shiftboss` fetches a remote block from a peer on demand during the query execution.

Use BlockLocator and DataExchangerAsync in the distributed tests.

---

CMakeLists.txt
cli/QuickstepCli.cpp
storage/StorageConstants.hpp

This small PR moved two storage-related constants into a header file so that other files in the distributed version would also use them.

Moved some storage-related constants.

---

query_execution/Shiftboss.cpp
query_execution/Shiftboss.hpp

This PR also adds a new method `processShiftbossRegistrationResponseMessage` to handle the message once at the start-up time.

Refactor Shiftboss for better debug info.

---

query_execution/PolicyEnforcerBase.cpp
query_execution/PolicyEnforcerBase.hpp
query_execution/QueryExecutionMessages.proto
query_execution/Worker.cpp
query_execution/Worker.hpp

This PR combined `WorkOrderCompletionMessage` for both normal and rebuild work orders. And it is required for the distributed version to refactor `PolicyEnforcerBase::decrementNumQueuedWorkOrders` to use `WorkOrderCompletionMessage` as the argument instead.

Unified WorkOrderCompletionMessage proto.

---

BUILDING.md
cli/QuickstepCli.cpp
storage/StorageConstants.hpp

This small PR keeps the catalog filename as a constant, so that Clis in the single-node and the distributed version could share it.

Maintained the catalog filename as a constant.

---

query_execution/CMakeLists.txt
query_execution/PolicyEnforcerBase.cpp
query_execution/PolicyEnforcerBase.hpp
query_execution/PolicyEnforcerDistributed.hpp
query_execution/PolicyEnforcerSingleNode.cpp
query_execution/PolicyEnforcerSingleNode.hpp
query_execution/QueryExecutionMessages.proto
query_execution/QueryExecutionTypedefs.hpp
query_execution/Shiftboss.cpp
query_execution/Shiftboss.hpp
query_execution/Worker.cpp
query_execution/Worker.hpp

Do not merge until #131 is merged.
This PR allows both the single-node and the distributed version to count `WorkOrder` in the different levels: per worker thread and per `Shiftboss` (or an execution site), respectively.

Decrement num queued work orders.

---

utility/CMakeLists.txt
utility/NetworkUtil.cpp
utility/NetworkUtil.hpp
utility/tests/NetworkUtil_unittest.cpp

This PR provides a method to get the ip address of the host machine. It will be used by `DataExchanger` in the distributed version.
Note that this util method does not have a `WINDOWS` implementation yet.

Added an util method to get the ip address.

---

storage/CMakeLists.txt
storage/DataExchangerAsync.cpp
storage/DataExchangerAsync.hpp

Do not merge until #132 is in.
This PR allows the `DataExchanger` to use the actual ip address, instead of the local `0.0.0.0`.

Ethernet data exchanger.

---

query_execution/CMakeLists.txt
query_execution/ForemanDistributed.cpp
query_execution/ForemanDistributed.hpp
query_execution/PolicyEnforcerDistributed.cpp
query_execution/PolicyEnforcerDistributed.hpp
query_execution/QueryExecutionState.hpp
query_execution/QueryManagerDistributed.cpp
query_execution/QueryManagerDistributed.hpp

Do not merge until #137 is in.
This PR allows the distributed unit test to use multi-Shiftboss so that it simulates the full-functional distributed query execution engine.
Note that this naive `WorkOrder` scheduling implementation uses a simple round-robin manner.

Distributed Multi-shiftboss Query Execution Unit Test

---

cli/CommandExecutor.cpp
cli/QuickstepCli.cpp
cli/tests/CommandExecutorTestRunner.cpp
query_execution/QueryManagerBase.hpp
query_execution/tests/QueryManagerSingleNode_unittest.cpp
query_optimizer/tests/DistributedExecutionGeneratorTestRunner.cpp
query_optimizer/tests/ExecutionGeneratorTestRunner.cpp

This PR allows the `QueryManager` to take over `QueryHandle` during the query execution, thus it is easier for the distributed version to execute the concurrent queries w/o worrying about the ownership of each `QueryHandle`.

Transferred the ownership of QueryHandle to QueryManager.

---

query_execution/ForemanDistributed.cpp
query_execution/PolicyEnforcerDistributed.hpp
query_optimizer/ExecutionGenerator.cpp
query_optimizer/QueryHandle.hpp

This PR avoids the following incorrect situation:
1. An insert query has executed on Node 0, so the affected block is in the buffer pool.
1. Another insert query on the same relation as above is supposed to be scheduled on Node 1, which will pull the block from Node 0, and do the insertion.
1. A select query on the same relation may be scheduled on Node 0, but will miss the tuples inserted on Node 1.

Marked SingleNodeQuery for Insertions.

---

CMakeLists.txt
cli/CMakeLists.txt
cli/distributed/CMakeLists.txt
cli/distributed/Cli.cpp
cli/distributed/Cli.hpp
cli/distributed/CliDistributedModule.hpp
cli/distributed/Conductor.cpp
cli/distributed/Conductor.hpp
cli/distributed/Executor.cpp
cli/distributed/Executor.hpp
cli/distributed/QuickstepDistributedCli.cpp
cli/distributed/Role.cpp
cli/distributed/Role.hpp
query_execution/QueryExecutionMessages.proto
query_execution/QueryExecutionTypedefs.hpp
validate_cmakelists.py

Hi, @pateljm 
This PR added a single binary for the distributed version with the cmake config `-DENABLE_DISTRIBUTED=ON`. Note that it requires `proto3` and `grpc` to build. On Mac, we could simply [use `brew`](https://github.com/grpc/homebrew-grpc) to install them.
To run the multiple-`Shiftboss`, distributed Quickstep, we use the following commands:
```
$ cd build
$ mkdir distributed
$ cd distributed
$ mkdir cli cli2 conductor executor executor2
$ mkdir cli/qsstor cli2/qsstor executor/qsstor executor2/qsstor
Terminal0 $ ../third_party/tmb/tmb_net_server --tmb_implementation=purememory
Terminal1 $ cd conductor && ../../quickstep_distributed_cli_shell --role=conductor --initialize_db
Terminal2 $ cd executor && ../../quickstep_distributed_cli_shell --role=executor
Terminal3 $ cd cli && …
```

Added DistributedCli executable.

---

CMakeLists.txt

Quickstep build on Mac OSX 10.12 fails due to deprecation of certain system APIs in the new OSX version. The Quickstep code does not rely on these deprecated APIs, but it is the protobuf library which uses these deprecated APIs. [See: https://github.com/google/protobuf/issues/2182]
Although, this has been resolved in the latest master of protobuf [See: https://github.com/google/protobuf/pull/2337], Quickstep protobuf cmake integration file has to be updated resolve this.
As this is turning out to be a blocker for the dev environment, this JIRA proposes a quick short-term fix for this issue by specifically turning off deprecation errors on OSX 10.12 platform. The more stable long-term fix would be to port the protobuf_cmake to the newest protobuf version. However, that requires some …

QUICKSTEP-65 Fix Quickstep build failure on Mac OSX 10.12

---

query_optimizer/cost_model/CostModel.hpp
query_optimizer/cost_model/SimpleCostModel.cpp
query_optimizer/cost_model/StarSchemaSimpleCostModel.cpp
utility/PlanVisualizer.cpp

`PlanVisualizer` would result in crashes on some queries (i.e., `CreateTable`) which do not have corresponding physical plan support in `StarSchemaSimpleCostModel::estimateCardinality`.
This PR fixes this problem by:
(1) Let the cost models throw `UnsupportedPhysicalPlan` exception for unsupported plans.
(2) `PlanVisualizer` simply catches the exceptions and omits the cardinality info for unsupported physical nodes.
Assigned to @zuyu

Quickstep-63 Fix PlanVisualizer's crashes on physical plans unsupported by StarSchemaSimpleCostModel.

---

catalog/CMakeLists.txt
catalog/Catalog.proto
catalog/CatalogRelationStatistics.cpp
catalog/CatalogRelationStatistics.hpp
cli/CMakeLists.txt
cli/CommandExecutor.cpp
query_optimizer/ExecutionGenerator.cpp
query_optimizer/cost_model/CMakeLists.txt
query_optimizer/cost_model/SimpleCostModel.cpp
query_optimizer/cost_model/StarSchemaSimpleCostModel.cpp
relational_operators/CMakeLists.txt
relational_operators/SaveBlocksOperator.cpp
relational_operators/SaveBlocksOperator.hpp

This PR collects the min/max statistics for each column of a table with the `\analyze` command. It also adds an `is_exact_` flag into `CatalogRelationStatistic` to indicate whether the statistics reflect the exact (i.e. not approximate) properties of the current data. Each table's `is_exact_` flag will be set to `true` with the `\analyze` command on that table, and will be set to `false` with the  _insert/delete/update/copy_ operations on that table.
This PR is a preparation for implementing some fast-path operators (e.g. exact filters and vector-based aggregation) that significantly improve Quickstep's performance on some of the SSB/TPC-H queries.
**NOTE**: With this PR the system will be incompatible with previously created databases due to some changes in `Catalog.proto`. In fact, we …

Add min/max statistics and the exactness flag into CatalogRelationStatistic

---

query_optimizer/ExecutionGenerator.cpp
relational_operators/SaveBlocksOperator.hpp

Fixed the distributed unit test failures introduced in #155.

Fixed the distributed unit test failures in resetting exactness for InsertSelect.

---

catalog/CMakeLists.txt
catalog/Catalog.proto
catalog/CatalogRelation.cpp
catalog/PartitionScheme.cpp
catalog/PartitionScheme.hpp
catalog/PartitionSchemeHeader.cpp
catalog/PartitionSchemeHeader.hpp
catalog/tests/PartitionScheme_unittest.cpp
storage/InsertDestination.cpp

This small PR simplified the `PartitionSchemeHeader` reconstruction method, which will be used in `Resolver` for the `CreateTable` statement, by moving `type` used for `RangePartition` only into its proto.

Refactored the method to reconstruct PartitionSchemeHeader.

---

relational_operators/SelectOperator.cpp
relational_operators/SelectOperator.hpp

This PR simplified `SelectOperator::getAllWorkOrders`, and allows to generate `WorkOrder`s when the input relation has data partitions, but not in the `NUMA` case.

Refactored SelectOperator::getAllWorkOrders.

---

query_execution/tests/QueryManagerSingleNode_unittest.cpp
relational_operators/AggregationOperator.hpp
relational_operators/BuildHashOperator.hpp
relational_operators/DeleteOperator.hpp
relational_operators/HashJoinOperator.hpp
relational_operators/NestedLoopsJoinOperator.cpp
relational_operators/NestedLoopsJoinOperator.hpp
relational_operators/RelationalOperator.hpp
relational_operators/SampleOperator.hpp
relational_operators/SaveBlocksOperator.cpp
relational_operators/SaveBlocksOperator.hpp
relational_operators/SelectOperator.hpp
relational_operators/SortMergeRunOperator.hpp
relational_operators/SortRunGenerationOperator.hpp
relational_operators/TableGeneratorOperator.hpp
relational_operators/tests/SortMergeRunOperator_unittest.cpp

This small PR removed the unused `feedInputBlocks` in `RelationalOperator`s for passing partially filled blocks to the operator.
Even worse, there is a follow-up PR that adds `partition_id` in `feedInputBlock`, the existing `feedInputBlocks` would be hard to adapt w/ partition info.

Removed the unused feedInputBlocks.

---

query_execution/PolicyEnforcerBase.cpp
query_execution/QueryExecutionMessages.proto
query_execution/QueryManagerBase.cpp
query_execution/QueryManagerBase.hpp
query_execution/tests/QueryManagerSingleNode_unittest.cpp
relational_operators/AggregationOperator.hpp
relational_operators/BuildHashOperator.hpp
relational_operators/DeleteOperator.hpp
relational_operators/HashJoinOperator.hpp
relational_operators/NestedLoopsJoinOperator.hpp
relational_operators/RelationalOperator.hpp
relational_operators/SampleOperator.hpp
relational_operators/SaveBlocksOperator.hpp
relational_operators/SelectOperator.hpp
relational_operators/SortMergeRunOperator.hpp
relational_operators/SortRunGenerationOperator.hpp
relational_operators/tests/SortMergeRunOperator_unittest.cpp
storage/InsertDestination.cpp
storage/InsertDestination.hpp

As a part of adding partition support, this PR added an optional `partition_id` in `RelationalOperator::feedInputBlock`.
Assigned to @hbdeshmukh. Thanks!

Added partition_id in RelationalOperator::feedInputBlock.

---

query_execution/QueryContext.cpp
query_execution/QueryContext.hpp
query_execution/QueryContext.proto
query_optimizer/ExecutionGenerator.cpp
relational_operators/BuildHashOperator.cpp
relational_operators/BuildHashOperator.hpp
relational_operators/CMakeLists.txt
relational_operators/DestroyHashOperator.cpp
relational_operators/DestroyHashOperator.hpp
relational_operators/HashJoinOperator.cpp
relational_operators/HashJoinOperator.hpp
relational_operators/WorkOrder.proto
relational_operators/WorkOrderFactory.cpp
relational_operators/tests/HashJoinOperator_unittest.cpp
storage/StorageBlockInfo.hpp

Assigned to @hbdeshmukh or @jianqiao.
This PR allows `HashJoin` to accept partitioned info. If no partition, `num_partitions` is `1`.

Added Operator support for Partitioned HashJoin.

---

catalog/CMakeLists.txt
catalog/tests/CatalogRelationStatistics_unittest.cpp

This PR adds unit tests for CatalogRelationStatistics. It tests that the `\analyze` command can produce correct stats, and that the `is_exact_` flag be set properly with insert / update / delete / analyze operations.

Add unit test for CatalogRelationStatistics

---

query_optimizer/CMakeLists.txt
query_optimizer/PhysicalGenerator.cpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/ReorderColumns.cpp
query_optimizer/rules/ReorderColumns.hpp
query_optimizer/tests/OptimizerTextTest.cpp
relational_operators/CMakeLists.txt
relational_operators/HashJoinOperator.cpp
relational_operators/HashJoinOperator.hpp
storage/SplitRowStoreValueAccessor.hpp
storage/ValueAccessor.hpp
types/containers/ColumnVectorsValueAccessor.hpp

Currently, all the intermediate relations (i.e. temporary relations created during query execution) have `SPLIT_ROW_STORE` layouts. One existing optimization that improves copy performance for `SPLIT_ROW_STORE` layout is that, if two (or more) attributes are consecutive in both the source relation and the destination relation, then we can memory-copy the attributes' byte stream with just one `std::memcpy` call.
This PR is a complementary improvement that it adjusts the ordering of the attributes in the physical plan to maximize the opportunity of copying consecutive attributes – i.e. to minimize the number of `std::memcpy` calls.
This PR uses a simple greedy algorithm to reorder the attributes, which works well with SSB/TPCH workloads. The algorithm may be further improved later.
The …

QUICKSTEP-68 Reorder intermediate relations'  attributes to improve copy performance.

---

query_optimizer/CMakeLists.txt
query_optimizer/PhysicalGenerator.cpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/PushDownLowCostDisjunctivePredicate.cpp
query_optimizer/rules/PushDownLowCostDisjunctivePredicate.hpp

This PR implements an optimization (physical plan transformation) that pushes down disjunctive predicate to filter stored relations early when proper conditions are met.
Here we elaborate the conditions. Let
```
P = p_{1,1} AND ... AND p_{1, m_1}
OR
...
OR
p_{n,1} AND ... AND p_{n, m_n}
```
be a predicate in _disjunctive normal form_.
Now consider each small-cardinality relation R, if for each `i` in `1..n`, there exists at least one predicate `p_{i, k_i}` that is applicable to R. Then we can construct a new predicate
```
P' = p_{1, k_1} OR ... OR p_{n, k_n}
```
and push down `P'` to be applied to R.
Also, if any conjunctive component in `P` contains more than one predicate that is applicable to R, then we can combine all these applicable predicates as a conjunctive component in `P'`. …

Push down disjunctive predicates to filter small-cardinality stored relation early.

---

query_optimizer/rules/AttachLIPFilters.cpp
utility/lip_filter/SingleIdentityHashFilter.hpp

This PR fixes the problem with `SingleIdentityHashFilter` when the estimated filter cardinality is 0 (by setting the filter cardinality to at least 64).

Fix the bug with SingleIdentityHashFilter when filter_cardinality is 0.

---

query_optimizer/CMakeLists.txt
query_optimizer/Optimizer.cpp
query_optimizer/Optimizer.hpp
query_optimizer/PhysicalGenerator.cpp
query_optimizer/PhysicalGenerator.hpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/ReduceGroupByAttributes.cpp
query_optimizer/rules/ReduceGroupByAttributes.hpp
query_optimizer/tests/OptimizerTest.cpp
query_optimizer/tests/OptimizerTextTestRunner.cpp
query_optimizer/tests/OptimizerTextTestRunner.hpp

This PR implements an optimization (physical plan transformation) that pulls a table up an aggregation if many of that table's attributes serve as group-by attributes in the aggregation. We do the optimization because it is relatively slow to aggregate with a large set of group-by attributes, as well as to avoid copying the table's many attributes all the way up a chain of operators.
This optimization improves the performance of TPC-H Q10 to ~5.7s, with scale factor 100 on a cloudlab machine. Below shows the physical plans for TPC-H Q10 with/without the optimization.
[WithoutReduce.pdf](https://github.com/apache/incubator-quickstep/files/753410/WithoutReduce.pdf)
[WithReduce.pdf](https://github.com/apache/incubator-quickstep/files/753411/WithReduce.pdf)

Reduce the number of group-by attributes by pulling tables up aggregation.

---

query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
query_optimizer/ExecutionGenerator.hpp
query_optimizer/PhysicalGenerator.cpp
query_optimizer/cost_model/CMakeLists.txt
query_optimizer/cost_model/SimpleCostModel.cpp
query_optimizer/cost_model/SimpleCostModel.hpp
query_optimizer/cost_model/StarSchemaSimpleCostModel.cpp
query_optimizer/cost_model/StarSchemaSimpleCostModel.hpp
query_optimizer/physical/CMakeLists.txt
query_optimizer/physical/CrossReferenceCoalesceAggregate.cpp
query_optimizer/physical/CrossReferenceCoalesceAggregate.hpp
query_optimizer/physical/PatternMatcher.hpp
query_optimizer/physical/PhysicalType.hpp
query_optimizer/rules/BottomUpRule.hpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/FuseAggregateJoin.cpp
query_optimizer/rules/FuseAggregateJoin.hpp
relational_operators/BuildAggregationExistenceMapOperator.cpp
relational_operators/BuildAggregationExistenceMapOperator.hpp
relational_operators/CMakeLists.txt
relational_operators/WorkOrder.proto
relational_operators/WorkOrderFactory.cpp
storage/AggregationOperationState.cpp
storage/AggregationOperationState.hpp
storage/CollisionFreeVectorTable.hpp
utility/lip_filter/BitVectorExactFilter.hpp
utility/lip_filter/CMakeLists.txt
utility/lip_filter/SingleIdentityHashFilter.hpp

This PR fuses `Aggregate` with `HashJoin` (left outer) into the `CrossReferenceCoalesceAggregate` node to enable fast-path evaluation for a class of queries.
Here we briefly describe the semantics of `CrossReferenceCoalesceAggregate`: Let `L` be a table with PRIMARY KEY `u`. Let `R` be a table with FOREIGN KEY `x` referring to `L(u)`. Then `CrossReferenceCoalesceAggregate` represents a common class of analytical queries that
> For each u in L, COUNT/SUM the records in R that correspond to u (i.e. those records satisfying R.x = L.u). In the case that there is no record for u in R, use 0 as the result value.
That is, `CrossReferenceCoalesceAggregate` represents queries in the following forms:
```
-- Form 1 --
SELECT u, COALESCE(count, 0), COALESCE(sum, 0)
FROM L LEFT OUTER JOIN (
SELECT x, …
```

Fuse Aggregate with HashLeftOuterJoin to accelerate evaluation

---

third_party/src/tmb/CMakeLists.txt
third_party/src/tmb/include/tmb/message_bus.h
third_party/src/tmb/src/message_bus.cc

`kReceivePollIntervalMS` is the key to the performance of the distributed version. And by making it as a `gflag`, we could change the value to tune the system performance w/o recompiling.

Defined TMB Message Poll Interval as a gflag.

---

third_party/download_and_patch_prerequisites.sh
third_party/patches/linenoise/linenoise.c.patch
third_party/patches/linenoise/linenoise.h.patch

This fixes an issue where newlines were not being given to quickstep's parser. These changes existed previously in quickstep but were not carried over in #166

patches for missed linenoise changes

---

cli/distributed/Executor.cpp
query_execution/CMakeLists.txt
query_execution/Shiftboss.cpp
query_execution/Shiftboss.hpp
query_optimizer/tests/DistributedExecutionGeneratorTestRunner.cpp
relational_operators/CMakeLists.txt
relational_operators/TextScanOperator.cpp
relational_operators/TextScanOperator.hpp
relational_operators/WorkOrderFactory.cpp
relational_operators/WorkOrderFactory.hpp
storage/FileManagerHdfs.hpp
storage/StorageManager.cpp
storage/StorageManager.hpp

This PR allows to bulk load files to HDFS used in the distributed version. It also fixed the file pointer leak when an read exception throws.
Note that we need to read twice for a row, if the row spans in two HDFS blocks. Otherwise, it is faulty, and affect the correctness of the query result.

Added HDFS Support For TextScanWorkOrder.

---

third_party/download_and_patch_prerequisites.sh
third_party/patches/gflags/gflags_reporting.cc.patch

This fix adds a patch to the third party library `gflags` so that compilation will work with certain versions of GCC which were previously erroring on a warn->error for an unsigned to signed conversion.
@jianqiao

patch to fix gcc compile error gflags

---

storage/PackedPayloadHashTable.cpp

This PR fixes the gcc build error (missing `this` pointer for calling a method in a capture-all-by-reference lambda function).
Note: Modified `travis.yml` for testing, do not merge yet.

Fix gcc build error with PackedPayloadHashTable 

---

relational_operators/SelectOperator.hpp
relational_operators/tests/SortRunGenerationOperator_unittest.cpp

This PR fixes a bug that `SELECT ... LIMIT n;` may output more than `n` rows.
The cause is that `SortMergeRunOperator` creates two relations, where one relation is the output relation to a `SelectOperator` and the other is a _temporary_ relation. However, the generated blocks of the temporary relation are also fed into the `SelectOperator` via a _DataPipelineMessage_ -- thus we need to check that the input block to a `SelectOperator` is actually from its input relation.

Fix a bug with SelectOperator

---

third_party/download_and_patch_prerequisites.sh

In prep for RC6, @zuyu recommended making a small change to the patch script. 
Now it should be explicit as to exactly what files are being patched.
Post-patch example output
```bash
...
patching file /Users/cramja/workspace/quickstep/incubator-quickstep/third_party/src/linenoise/linenoise.h
patching file /Users/cramja/workspace/quickstep/incubator-quickstep/third_party/src/linenoise/linenoise.c
patching file /Users/cramja/workspace/quickstep/incubator-quickstep/third_party/src/gflags/CMakeLists.txt
patching file /Users/cramja/workspace/quickstep/incubator-quickstep/third_party/src/gflags/src/gflags_reporting.cc
patching file /Users/cramja/workspace/quickstep/incubator-quickstep/third_party/src/re2/CMakeLists.txt
patching file /Users/cramja/workspace/quickstep/incubator-quickstep/third_par …
```

simplify logic of download script

---

CMakeLists.txt

This fixes two annoying build issues
1. If the CMAKEBUILDTYPE is not set by the user, it previously defaulted to none-type which caused one of our tests to fail. It is now set to RelWithDebInfo if no build type is set. Code take from [link](https://github.com/miloyip/rapidjson/issues/319)
2. When building on Mac, the default setting of TCMALLOC would cause a compiler error. We fix this by disabling TCMALLOC on Mac

Cmake changes for default build

---

release/release_cmds.sh

Minor bugfixes to the release scripts. Previously I was saving the wrong directories to environment variables. Also, adding grep to one of the commands makes it work predictably.

fixes bug in ordering of cmds

---

query_execution/PolicyEnforcerBase.cpp

This PR fixed the bug in `admitQueries` that if an `AdmitRequestMessage` contains a number of queries that excesses that can be admitted to the system, the excessed queries would be lost.
Instead, now we add these overflowed queries to a waiting list so that they will be scheduled later.

Fixed a bug in admitQueries.

---

catalog/PartitionSchemeHeader.cpp

This small PR reuses `PartitionSchemeHeader::getProto` from the base class in `RangePartitionSchemeHeader::getProto`.

Minor refactored RangePartitionSchemeHeader::getProto.

---

query_execution/Shiftboss.hpp

This small PR removes `;` after the namespace scope.

Fixed a pedantic warning.

---

catalog/CMakeLists.txt
catalog/Catalog.proto
catalog/CatalogRelation.cpp
catalog/PartitionSchemeHeader.cpp
catalog/PartitionSchemeHeader.hpp
catalog/tests/NUMAPlacementScheme_unittest.cpp
catalog/tests/PartitionScheme_unittest.cpp
parser/tests/Create.test
query_optimizer/ExecutionGenerator.cpp
query_optimizer/resolver/Resolver.cpp
query_optimizer/tests/execution_generator/Create.test
query_optimizer/tests/logical_generator/Create.test
query_optimizer/tests/physical_generator/Create.test
query_optimizer/tests/resolver/Create.test
relational_operators/tests/HashJoinOperator_unittest.cpp
storage/CMakeLists.txt
storage/InsertDestination.cpp
storage/InsertDestination.hpp
storage/InsertDestinationInterface.hpp
storage/StorageBlock.cpp

This PR added multi-attribute partitions support.
```
CREATE TABLE foo5 (attr1 INT, attr2 LONG, attr3 FLOAT, attr4 DOUBLE, attr5 CHAR(5),
attr6 VARCHAR(4))
PARTITION BY HASH(attr1, attr2, attr3, attr4, attr5, attr6) PARTITIONS 4;
```

QUICKSTEP-73: Multi-attribute PartitionSchemeHeader.

---

storage/AggregationOperationState.cpp
storage/PackedPayloadHashTable.cpp
storage/PackedPayloadHashTable.hpp

This PR fixes a bug in `PackedPayloadHashTable` when `derived_accessor` is of type `TupleIdSequenceAdapterValueAccessor<ColumnVectorsValueAccesor>`.
Thanks Harshad @hbdeshmukh for pointing out the problem!

Fix a bug in PackedPayloadHashTable

---

catalog/CatalogRelation.hpp
query_execution/CMakeLists.txt
query_execution/QueryContext.cpp
query_execution/QueryContext.hpp
query_execution/QueryManagerBase.hpp
query_execution/QueryManagerSingleNode.cpp
query_execution/QueryManagerSingleNode.hpp
storage/AggregationOperationState.cpp
storage/AggregationOperationState.hpp
storage/CollisionFreeVectorTable.hpp
storage/HashTable.hpp
storage/HashTableBase.hpp
storage/HashTablePool.hpp
storage/LinearOpenAddressingHashTable.hpp
storage/PackedPayloadHashTable.hpp
storage/PartitionedHashTablePool.hpp
storage/SeparateChainingHashTable.hpp
storage/SimpleScalarSeparateChainingHashTable.hpp

- Methods to get memory footprints of join hash tables (for all of its
implementations)
- Method to get the memory consumed by the active temporary relations
during the query execution.
- Added methods for measuring memory consumed by hash tables used for
aggregation.
- AggregationOperationState can provide total memory used for a single
aggregation node.
- QueryContext can aggregate the memory consumed by all temporary data
structures (e.g. join hash tables, aggregation hash tables).
- QueryManagerBase provides an API to get the total memory footprint of
a query (only implemented for single node version).
- Mutex protection for hash join tables' list and insert destinations' list in
the QueryContext class.

QUICKSTEP-83 Measure memory consumption of a running query

---

query_execution/tests/QueryManagerSingleNode_unittest.cpp
relational_operators/AggregationOperator.hpp
relational_operators/BuildAggregationExistenceMapOperator.hpp
relational_operators/BuildHashOperator.hpp
relational_operators/BuildLIPFilterOperator.hpp
relational_operators/CreateIndexOperator.hpp
relational_operators/CreateTableOperator.hpp
relational_operators/DeleteOperator.hpp
relational_operators/DestroyAggregationStateOperator.hpp
relational_operators/DestroyHashOperator.hpp
relational_operators/DropTableOperator.hpp
relational_operators/FinalizeAggregationOperator.hpp
relational_operators/HashJoinOperator.hpp
relational_operators/InitializeAggregationOperator.hpp
relational_operators/InsertOperator.hpp
relational_operators/NestedLoopsJoinOperator.hpp
relational_operators/RelationalOperator.hpp
relational_operators/SampleOperator.hpp
relational_operators/SaveBlocksOperator.hpp
relational_operators/SelectOperator.hpp
relational_operators/SortMergeRunOperator.hpp
relational_operators/SortRunGenerationOperator.hpp
relational_operators/TableGeneratorOperator.hpp
relational_operators/TextScanOperator.hpp
relational_operators/UpdateOperator.hpp
relational_operators/WindowAggregationOperator.hpp
storage/AggregationOperationState.cpp
storage/PartitionedHashTablePool.hpp

The goal of this PR is that the scheduler should be able to identify individual operations in the query plan DAG.

Added an enum type for all relational operators

---

CMakeLists.txt
cmake/QsProtobufGenerateCpp.cmake

Refactored out the GenProto methods from the main cmakelist. This cuts down on clutter and is something I ran into when making the single-node-server.
I also added some comments in the new cmake file.
@zuyu could you review?

Refactored out proto GenerateCPP function

---

query_execution/WorkOrdersContainer.hpp

The total count includes normal and rebuild work orders.

API to get total pending work orders for an operator

---

query_optimizer/ExecutionGenerator.cpp
query_optimizer/cost_model/StarSchemaSimpleCostModel.cpp
query_optimizer/cost_model/StarSchemaSimpleCostModel.hpp
storage/AggregationOperationState.cpp
storage/AggregationOperationState.hpp
storage/CMakeLists.txt
storage/CollisionFreeVectorTable.hpp
storage/HashTable.proto
storage/HashTableBase.hpp
storage/HashTableFactory.hpp
storage/HashTablePool.hpp
storage/PackedPayloadHashTable.hpp
storage/ThreadPrivateCompactKeyHashTable.cpp
storage/ThreadPrivateCompactKeyHashTable.hpp

This PR implements a new specialized aggregation hash table that is preferable for two-phase (i.e. aggregate locally and then merge) aggregation with small-cardinality group-by keys. To use this hash table, it also requires that the group-by keys have fixed-length types with total byte size no greater than 8 (so that each composite key can be packed into a 64-bit QWORD).
This PR together with #237 can improve the performance TPC-H Q01 from ~11.5s to ~5.3s, with scale factor 100 on a cloud lab machine.

Add ThreadPrivateCompactKeyHashTable for aggregation.

---

query_execution/QueryManagerSingleNode.cpp
query_execution/Shiftboss.cpp
relational_operators/RebuildWorkOrder.hpp
storage/InsertDestination.cpp
storage/InsertDestination.hpp

This PR fixed the bug when the input relation has partitions, but lost the info during the rebuild phase.

Assigned partition_id to RebuildWorkOrder.

---

CMakeLists.txt
cli/CMakeLists.txt
cli/IOInterface.hpp
cli/LineReaderBuffered.cpp
cli/LineReaderBuffered.hpp
cli/LocalIO.hpp
cli/NetworkCli.proto
cli/NetworkCliClient.hpp
cli/NetworkCliClientMain.cpp
cli/NetworkIO.cpp
cli/NetworkIO.hpp
cli/QuickstepCli.cpp
cli/tests/CMakeLists.txt
cli/tests/LineReaderBuffered_unittest.cpp
cli/tests/NetworkIO_unittest.cpp
validate_cmakelists.py

**Functional Changes include:**
]Adding a network mode to the cli. Run quickstep in `network` mode (defaults to `local`)
`quickstep_cli_shell --mode=network`
Now quickstep boots a server, you can interact using the client executable...
`quickstep_client < my_query.sql`
**Code Changes include:**
* Adds a generic IO interface
* Hides Linereader from CLI behind class `LocalIO`
* New `NetworkIO` also hidden here
* Adds tests for NetworkIO
* Adds simple Client executable 
* Cmake flag to disable (`ENABLE_NETWORK_CLI=false`)

QUICKSTEP-87 Adds network cli interface.

---

parser/SqlLexer.lpp
parser/preprocessed/SqlLexer_gen.cpp
parser/preprocessed/SqlLexer_gen.hpp
parser/preprocessed/SqlParser_gen.cpp
parser/preprocessed/SqlParser_gen.hpp

This small PR fixed the bug that commands like `\d`, `\dt`, and `\analyze` could not accept a table name that contains `_`:
```
quickstep> \analyze foo_part_4
ERROR: illegal character (1 : 14)
\analyze foo_part_4
^
quickstep> \d foo_part_4
ERROR: illegal character (1 : 8)
\d foo_part_4
^
quickstep> \dt foo_part_4
ERROR: illegal character (1 : 9)
\dt foo_part_4
^
```
Now:
```
quickstep> \dt foo_part_4
List of relations
Name       | Type  | Blocks
+-----------+-------+---------+
foo_part_4 | table | 4
quickstep> \d foo_part_4
Table "foo_part_4"
Column | Type
+-------+-------+
a      | Int
quickstep> \analyze foo_part_4
Analyzing foo_part_4 ... done
```

Fixed a bug regarding the table name containing '_' in Commands.

---

query_execution/CMakeLists.txt
query_execution/ForemanDistributed.cpp
query_execution/PolicyEnforcerDistributed.cpp
query_execution/PolicyEnforcerDistributed.hpp
query_execution/QueryManagerDistributed.hpp

This PR allows the distributed version to deterministically dispatch `BuildHashJoin` and `Aggregation` based on block locality. Previously, the dispatch algorithm naively uses a round-robin approach.

Dispatch BuildHashJoin and Aggregation based on block locality.

---

relational_operators/WorkOrderFactory.cpp

This small PR logs the partition id during the `WorkOrder` reconstruction.

Print the partition id in WorkOrder Reconstruction.

---

query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/ExtractCommonSubexpression.cpp
query_optimizer/rules/ExtractCommonSubexpression.hpp

This small PR simplified PR #237 by deriving from a `BottomUpRule`.

Simplified ExtractCommonSubexpression rule as a BottomUp rule.

---

relational_operators/BuildHashOperator.hpp
relational_operators/HashJoinOperator.cpp
relational_operators/HashJoinOperator.hpp

If the build side does not have partitions, but the probe does, the build side will be broadcast to each and every partition of the probe side.

Refactored the operator support for broadcast hash join.

---

cli/distributed/QuickstepDistributedCli.cpp
query_execution/CMakeLists.txt
query_execution/ForemanDistributed.cpp
query_execution/ForemanDistributed.hpp
query_execution/PolicyEnforcerDistributed.cpp
query_execution/PolicyEnforcerDistributed.hpp
query_execution/QueryManagerDistributed.cpp
query_execution/QueryManagerDistributed.hpp
query_optimizer/LIPFilterGenerator.cpp
query_optimizer/tests/DistributedExecutionGeneratorTest.cpp
relational_operators/AggregationOperator.cpp
relational_operators/BuildHashOperator.cpp
relational_operators/BuildLIPFilterOperator.cpp
relational_operators/HashJoinOperator.cpp
relational_operators/RelationalOperator.hpp
relational_operators/SelectOperator.cpp
relational_operators/WorkOrder.proto

This PR enables LIP feature in the distributed version. By computing the LIP filter group (aka equivalence class) based on the LIP filter usages in a LIP deployment, any work orders that use a LIP filter from the same group will be scheduled to the same node.
In all SSB queries, since there is only one LIP filter group, when enabling LIP feature, all work orders that use any LIP will be scheduled to one node.
Note that this PR is not compatible with partitions, until partitioned aggregations are supported.

QUICKSTEP-76: Enabled LIP in the distributed version.

---

query_optimizer/ExecutionGenerator.cpp
relational_operators/BuildLIPFilterOperator.cpp
relational_operators/BuildLIPFilterOperator.hpp
relational_operators/CMakeLists.txt
relational_operators/WorkOrder.proto

This small PR allows `BuildLipFilter` to accept partitioned inputs. There will be follow-up PRs for the optimizer and execution support.

Added operator support for BuildLipFilter with partitioned inputs.

---

catalog/CMakeLists.txt
catalog/Catalog.proto
catalog/PartitionSchemeHeader.cpp
catalog/PartitionSchemeHeader.hpp
catalog/tests/PartitionScheme_unittest.cpp

This small PR adds a new partition scheme called `RandomPartitionSchemeHeader`. By random, one and only one partition will be assigned to a given tuple randomly and is uniform distributed.

Added RandomPartitionSchemeHeader.

---

query_execution/BlockLocator.hpp
query_execution/ForemanDistributed.cpp
query_execution/PolicyEnforcerDistributed.cpp
query_execution/PolicyEnforcerDistributed.hpp
query_execution/QueryContext.cpp
query_execution/QueryContext.hpp
query_execution/QueryContext.proto
query_execution/QueryManagerDistributed.cpp
query_execution/QueryManagerDistributed.hpp
query_optimizer/ExecutionGenerator.cpp
relational_operators/AggregationOperator.cpp
relational_operators/AggregationOperator.hpp
relational_operators/BuildAggregationExistenceMapOperator.cpp
relational_operators/BuildAggregationExistenceMapOperator.hpp
relational_operators/CMakeLists.txt
relational_operators/DestroyAggregationStateOperator.cpp
relational_operators/DestroyAggregationStateOperator.hpp
relational_operators/FinalizeAggregationOperator.cpp
relational_operators/FinalizeAggregationOperator.hpp
relational_operators/InitializeAggregationOperator.cpp
relational_operators/InitializeAggregationOperator.hpp
relational_operators/WorkOrder.proto
relational_operators/WorkOrderFactory.cpp
relational_operators/tests/AggregationOperator_unittest.cpp

This PR added the support for aggregations with partitioned input relations.
Note that in the distributed version, supports for parallel aggregations based on `COLLISION_FREE_VECTOR` will need some discussion on the implementations. For now, I have two ideas, one is to fix the number of internal partitions of aggregations in the optimizer, and the other is to add support for the batched work order, which means that although `ForemanDistributed` sends one work order proto, such work order proto would generate multiple work orders for the same operator. In this case, it is the number of internal partitions for the aggregations.

Added the support for partitioned (but not parallel) aggregations.

---

cli/distributed/QuickstepDistributedCli.cpp
query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
query_optimizer/PhysicalGenerator.cpp
query_optimizer/physical/FilterJoin.cpp
query_optimizer/physical/FilterJoin.hpp
query_optimizer/physical/Physical.hpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/InjectJoinFilters.cpp
query_optimizer/rules/Partition.cpp
query_optimizer/rules/Partition.hpp
query_optimizer/rules/tests/CMakeLists.txt
query_optimizer/rules/tests/Partition_unittest.cpp
query_optimizer/tests/execution_generator/Partition.test

This PR substitutes #241 to add support for partitioned hash join. The rule adds repartitions if needed as follows:
```
/*
* Whether left or right side needs to repartition.
*
* --------------------------------------------------------------------------
* | Right \ Left     | No Partition  | Hash Partition h' | Other Partition |
* --------------------------------------------------------------------------
* | No Partition     | false \ false |  false \ false    |  true \ true    |
* --------------------------------------------------------------------------
* | Hash Partition h | false \ true  | false# \ false    | false \ true    |
* --------------------------------------------------------------------------
* | Other Partition  |  true \ true  |   true \ false    |  true \ true    |
* …
```

Added Partition Rule for HashJoin.

---

query_optimizer/physical/Selection.cpp
query_optimizer/physical/Selection.hpp
query_optimizer/rules/CollapseSelection.cpp
query_optimizer/rules/ExtractCommonSubexpression.cpp
query_optimizer/rules/PushDownLowCostDisjunctivePredicate.cpp
query_optimizer/rules/ReorderColumns.cpp
query_optimizer/strategy/Selection.cpp

This small PR refactored the `Create` factory method, so that we could better use it for adding repartition support, including repartitioning a relation with some partitions to no partitions.

Refactored Create Factory Method for Physical Selection.

---

query_optimizer/rules/Partition.cpp

This small PR ensures that a Physical node with partitioned inputs would also produce partitioned output, if possible.

Ensure Physical node with partitioned inputs has partitioned output, if possible.

---

query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
relational_operators/FinalizeAggregationOperator.cpp
relational_operators/FinalizeAggregationOperator.hpp
relational_operators/tests/AggregationOperator_unittest.cpp
storage/AggregationOperationState.cpp
storage/AggregationOperationState.hpp
storage/AggregationOperationState.proto
storage/CMakeLists.txt
storage/CollisionFreeVectorTable.cpp
storage/CollisionFreeVectorTable.hpp
storage/HashTableFactory.hpp

This PR allows the optimizer to determine the number of partitions for an aggregation state hash table, instead of getting it during the run-time from the aggregation state.

Determine #Partitions for Aggr State Hash Table in the optimizer.

---

.travis.yml
cli/QuickstepCli.cpp
query_execution/ForemanBase.hpp
query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
relational_operators/InitializeAggregationOperator.cpp
relational_operators/InitializeAggregationOperator.hpp
storage/AggregationOperationState.cpp
storage/AggregationOperationState.hpp
storage/AggregationOperationState.proto
storage/CMakeLists.txt
storage/CollisionFreeVectorTable.cpp
storage/CollisionFreeVectorTable.hpp
storage/HashTable.proto
storage/HashTableFactory.hpp
storage/StorageConstants.hpp

This check failure happens for a query like `create table` statements.

Fixed the check failure if a query does not have profiling info.

---

types/operations/comparisons/LiteralComparators-inl.hpp

This PR fixes the bug with min/max aggregation (that produces incorrect results) when the aggregated column is stored with **leading-zero-truncation compression**.
The bug happens because the untyped value (i.e. a `const void *` pointer) obtained from the leading-zero-truncation compressed column's corresponding `ValueAccessor` is [the address of a temporary buffer](https://github.com/apache/incubator-quickstep/blob/master/storage/CompressedColumnStoreValueAccessor.hpp#L112) -- i.e. the value pointer becomes invalid when the next `accessor->next()` gets called. [Keeping the value pointer](https://github.com/apache/incubator-quickstep/blob/master/types/operations/comparisons/LiteralComparators-inl.hpp#L546) across [multiple iterations …

Fix a bug with min/max aggregation.

---

query_execution/QueryManagerBase.cpp
query_execution/QueryManagerDistributed.cpp
query_execution/QueryManagerSingleNode.cpp
query_execution/tests/QueryManagerSingleNode_unittest.cpp
relational_operators/DeleteOperator.cpp
relational_operators/DestroyAggregationStateOperator.cpp
relational_operators/DestroyHashOperator.cpp
relational_operators/DropTableOperator.cpp
relational_operators/FinalizeAggregationOperator.cpp
relational_operators/HashJoinOperator.cpp
relational_operators/InitializeAggregationOperator.cpp
relational_operators/InsertOperator.cpp
relational_operators/RelationalOperator.hpp
relational_operators/SampleOperator.cpp
relational_operators/TableGeneratorOperator.cpp
relational_operators/TextScanOperator.cpp
relational_operators/UpdateOperator.cpp
relational_operators/WindowAggregationOperator.cpp
relational_operators/tests/AggregationOperator_unittest.cpp
relational_operators/tests/HashJoinOperator_unittest.cpp
relational_operators/tests/TextScanOperator_unittest.cpp

This PR removed `informAllBlockingDependenciesMet`, as it is redundant with regards to `checkAllBlockingDependenciesMet` in the query execution engine. Note that the current implementation of `Foreman` ensure that `getAllWorkOrders` will not be called unless the dependencies are met.

Removed an unnecessary API in RelationalOperator.

---

catalog/CatalogRelation.hpp

Assigned to @jianqiao. And thanks for reporting this bug, which would never be caught by any unit tests.

Fixed the bug that missed assigning 'num_partitions_' in CatalogRelation.

---

relational_operators/SortMergeRunOperator.cpp
relational_operators/SortMergeRunOperator.hpp

This PR did some minor refactors in `SortMergeRunOperator`, including removal of an unnecessary variable `input_stream_done_`, and changing some impossible conditions into checks.

Minor refactored SortMergeRunOperator.

---

CMakeLists.txt
cli/Flags.cpp
cli/Flags.hpp
cli/IOInterface.hpp
cli/NetworkCliClientMain.cpp
cli/QuickstepCli.cpp
query_optimizer/tests/ExecutionGeneratorTestRunner.cpp
utility/CMakeLists.txt
utility/ScopedReassignment.hpp
utility/tests/ScopedReassignment_unittest.cpp

This PR redirects `stdout / stderr` to `io_handle->out() / io_handle->err()` (see [here](https://github.com/apache/incubator-quickstep/blob/fb9f856a78d947647406f661f3f3291e294bd266/cli/QuickstepCli.cpp#L309)) for transmitting the standard stream outputs to client in the network mode. It allows `quickstep_client` to use `COPY ... TO stdout ...` command to retrieve result table in CSV format.

Redirect stdout and stderr in network mode.

---

catalog/CMakeLists.txt
catalog/PartitionScheme.cpp
catalog/PartitionScheme.hpp
catalog/PartitionSchemeHeader.cpp
catalog/PartitionSchemeHeader.hpp
cli/CMakeLists.txt
cli/CommandExecutorUtil.cpp
cli/tests/command_executor/D.test

This PR displayed the partition info via `\d [table name]` as following:
```
Partition Info
PARTITION BY HASH ( col1 ) PARTITIONS 4
| 1 | 1 | 1 | 1 |
```

QUICKSTEP-78: Displayed Partition Info using \d.

---

query_optimizer/tests/execution_generator/Partition.test
relational_operators/NestedLoopsJoinOperator.cpp
relational_operators/NestedLoopsJoinOperator.hpp

This PR fixed a bug for partitioned NLJ w/ both stored relations. Otherwise, we may miss some tuples.
Also, this PR treats the right relation as a single partition to simplify the join execution.

Fixed a bug in partitioned NLJ.

---

query_optimizer/CMakeLists.txt
query_optimizer/OptimizerTree.hpp
query_optimizer/logical/CreateTable.cpp
query_optimizer/logical/CreateTable.hpp
query_optimizer/physical/CreateTable.cpp
query_optimizer/physical/CreateTable.hpp
query_optimizer/tests/logical_generator/Create.test
query_optimizer/tests/physical_generator/Create.test
query_optimizer/tests/resolver/Create.test

This PR displayed the partition info in the query plan.
```
CREATE TABLE foo (attr INT) PARTITION BY HASH(attr) PARTITIONS 4;
--
TopLevelPlan
+-plan=CreateTable[relation=foo]
| +-partition_scheme_header=ProtoDescription
| | +-Property=ProtoProperty[Property=partition_type,Value=hash]
| | +-Property=ProtoProperty[Property=num_partitions,Value=4]
| | +-Property=ProtoProperty[Property=partition_attr_id,Value=0]
| +-attributes=
|   +-AttributeReference[id=0,name=attr,relation=foo,type=Int]
+-output_attributes=
+-AttributeReference[id=0,name=attr,relation=foo,type=Int]
```

Printed out the partition info in QueryPlan.

---

query_optimizer/PhysicalGenerator.cpp

This small PR allows to prune columns after partition rule, and thus improve the query performance by avoiding unused attributes.

Prune columns after partition rule.

---

cli/CMakeLists.txt
cli/LineReader.cpp
cli/tests/command_executor/D.test
cli/tests/command_executor/Dt.test

This PR fixes a bug that the Quickstep REPL cannot recognize a command (e.g. `\d`, `\analyze`) if there are whitespaces or empty lines before the command.

QUICKSTEP-104 Fix the problem that LineReader cannot recognize a command if there are whitespaces before it.

---

query_execution/CMakeLists.txt
query_execution/ForemanDistributed.cpp
query_execution/ForemanSingleNode.cpp
query_execution/QueryManagerBase.cpp
query_execution/QueryManagerBase.hpp
query_execution/QueryManagerDistributed.cpp
query_execution/QueryManagerDistributed.hpp
query_execution/QueryManagerSingleNode.cpp
query_execution/QueryManagerSingleNode.hpp
query_execution/WorkOrdersContainer.hpp
query_execution/tests/QueryManagerSingleNode_unittest.cpp

This PR revisited the work order generation process in the query execution engine, including simplified the recursive method to `markOperatorFinished` from `processOperator`. This change improves performance for TPC-H SF-100, while simplifies the code base.
Assigned to @jianqiao, and CC'ed @hbdeshmukh.

Simplified the work order generation.

---

validate_cmakelists.py

This small PR allows not to print out the incorrect warning, when the forked codebase root directory name does not end up with `quickstep`.

Fixed the root path check in the validate_cmakelists script.

---

query_execution/CMakeLists.txt
query_execution/ExecutionStats.hpp

Stats are maintained for active operators in the query. Right now, the stats include number of work orders and the execution times of the work orders. The design of the class is open to future extensions to add fields such as number of rows read, peak memory consumption during a work order execution.

Created a class to track execution statistics

---

cyclic_dependency.py

A minor fix allows not to print out the incorrect warning, when the forked codebase root directory name does not end up with `quickstep`.

Fixed the root path check in the cyclic_dependency.py.

---

query_execution/QueryManagerDistributed.cpp
relational_operators/WorkOrderFactory.cpp

due to query execution engine simplification #281.
Note that Travis CI does not test the distributed version.

Fixed the distributed version

---

catalog/tests/Catalog_unittest.cpp

This small PR fixes a flaky test case of adding an index with a different name, but the same description. However, the adding description is empty due to previous move semantics.

Fixed a flaky case in Catalog test.

---

storage/InsertDestination.cpp
storage/InsertDestination.hpp
storage/InsertDestinationInterface.hpp

This PR cleans up the unused argument `always_mark_full`, and avoids branching overhead.

Removed unused argument always_mark_full.

---

query_execution/CMakeLists.txt
query_execution/ProbabilityStore.hpp
query_execution/tests/ProbabilityStore_unittest.cpp

- Used to store probabilities of objects.
- Probabilities are of two kinds: Individual and cumulative.
- All the individual probabilities within the store add up to one.
- Support for finding the object with given cumulative probability.
This PR is in continuation with the set of PRs for QUICKSTEP-107.

Added ProbabilityStore class

---

CMakeLists.txt

Added building support for OS X 10.13 (which didn't work beforehand)

Temporary Build Support for OS X 10.13

---

query_optimizer/CMakeLists.txt
query_optimizer/LogicalGenerator.cpp
query_optimizer/Optimizer.cpp
query_optimizer/Optimizer.hpp
query_optimizer/QueryHandle.hpp
query_optimizer/QueryProcessor.cpp
query_optimizer/QueryProcessor.hpp
query_optimizer/resolver/CMakeLists.txt
query_optimizer/resolver/Resolver.cpp
query_optimizer/resolver/Resolver.hpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/ReferencedBaseRelations.cpp
query_optimizer/rules/ReferencedBaseRelations.hpp

- Find the base relations that are referenced in a query.
- The referenced relations are stored in the QueryHandle.
- Separate method to just get this list of relations, without needing to fully optimize the query.

QUICKSTEP-112 Get the list of referenced base relations

---

query_optimizer/ExecutionGenerator.cpp
query_optimizer/tests/execution_generator/Partition.test

This PR fixed the bug that when some column gets pruned, the partition is incorrect due to the wrong logical catalog attribute id from the output relation.
We should use the old logical catalog attribute id from *the input relation*.

Fixed the bug when partition w/ pruned columns.

---

.travis.yml
CMakeLists.txt
types/operations/comparisons/AsciiStringComparators-inl.hpp
types/operations/comparisons/AsciiStringComparators.hpp
types/operations/comparisons/Comparison.cpp
types/operations/comparisons/LiteralComparators-inl.hpp
types/operations/comparisons/LiteralComparators.hpp

This PR adds a cmake option `ENABLE_COMPARISON_INLINE_EXPANSION` to allow disabling of method specialization in various `Comparison`'s.
Turing the flag `OFF` will greatly reduce Quickstep compile time -- thus improving development productivity as well as fixing the Travis CI timeout problem. Note that the flag is by default `ON`, and will be [turned off](https://github.com/apache/incubator-quickstep/blob/539e1ebe09b5d1a2d86069ed1fdc6e9fb38c5ce7/.travis.yml#L80) during the Travis test.

Add a cmake option to handle the Travis CI timeout problem.

---

third_party/src/iwyu/iwyu_helper.py

This PR fixes the third-party library include paths for the iwyu (include-what-you-use) tool.

Fix iwyu include path

---

relational_operators/TextScanOperator.cpp

This PR avoids the segfault mentioned [here](https://github.com/apache/incubator-quickstep/pull/336#issuecomment-370674172) when opening an input file that does not exist.

Check File Handle in TextScanWorkOrder to avoid segfault.

---

storage/StorageConstants.hpp
storage/StorageManager.cpp

Fixed the data exchange problem encountered in distributed quickstep.
It turned out that problem of data exchange is caused by the gRPC channel's limit on the maximum receive size (4 MiB, 4194304 Bytes).
In DataExchange.proto
`message PullResponse {
bool is_valid = 1;
uint64 num_slots = 2;
bytes block = 3;
}`
the block size is 4MiB (which is fine), but there are 9 bytes of overhead (num_slots 8 bytes and is_valid 1 byte). These extra bytes are the essential reason that the data exchange failed.
In this commit, I set the limit of maximum receive size to 4194213 (4MiB + 9bytes), which is right enough for us. 
With this commit, the distributed quickstep is able to pass ssb test with a scale factor of 10

Fixed the gRPC Problem for Data Exchange

---

cli/tests/CMakeLists.txt
cli/tests/CommandExecutorTest.cpp
cli/tests/CommandExecutorTestRunner.cpp
cli/tests/CommandExecutorTestRunner.hpp
cli/tests/command_executor/Analyze.test
cli/tests/command_executor/CMakeLists.txt
cli/tests/command_executor/D.test
cli/tests/command_executor/Dt.test
query_optimizer/CMakeLists.txt
query_optimizer/ExecutionGenerator.cpp
query_optimizer/Optimizer.cpp
query_optimizer/PhysicalGenerator.cpp
query_optimizer/PhysicalGenerator.hpp
query_optimizer/physical/Aggregate.cpp
query_optimizer/physical/Aggregate.hpp
query_optimizer/physical/CMakeLists.txt
query_optimizer/physical/HashJoin.cpp
query_optimizer/physical/HashJoin.hpp
query_optimizer/physical/NestedLoopsJoin.cpp
query_optimizer/physical/NestedLoopsJoin.hpp
query_optimizer/physical/PatternMatcher.hpp
query_optimizer/physical/Physical.hpp
query_optimizer/physical/Selection.cpp
query_optimizer/physical/Selection.hpp
query_optimizer/physical/UnionAll.hpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/EliminateEmptyNode.cpp
query_optimizer/rules/EliminateEmptyNode.hpp
query_optimizer/tests/OptimizerTextTestRunner.cpp
query_optimizer/tests/TestDatabaseLoader.cpp

This PR adds an optimization rule that eliminates a physical node with an empty (determined by stats) `TableReference` into a `Selection` on a temp table.

Quickstep-119: Added the rule that eliminates a node w/ an empty table.

---

query_optimizer/physical/FilterJoin.cpp
query_optimizer/physical/FilterJoin.hpp
query_optimizer/physical/PatternMatcher.hpp
query_optimizer/rules/InjectJoinFilters.cpp

Added the missing `has_repartition` in `FilterJoin`, also added it as a subtype of `BinaryJoin` in `PatternMatcher`.

QUICKSTEP-123: Fixed the missing 'has_repartition' in FilterJoin.

---

autofix_cmakelists.py

This PR adds a script that intends to help improve developer productivity by automatically fixing `CMakeLists.txt` files for the Quickstep project (with best effort).
The script will do the following things:
- Scan the repo's subdirectories and collect `#include` information from all source code files.
- Parse existing `CMakeLists.txt` files and convert all "recognized" commands into proper intermediate representations -- the "unrecognized" part will be kept as "verbal" lines.
- Resolve subdirectories, targets and link dependencies. Add / delete / update the corresponding entries.
- Convert the intermediate representations back to `CMakeLists.txt` files.
**NOTE:** Currently the script is at its initial stage and will not update tests or conditional targets (i.e. those within cmake `if` …

QUICKSTEP-124: Add a python script to auto fix CMakeLists files

---

cli/tests/command_executor/Analyze.test
query_optimizer/ExecutionGenerator.cpp
query_optimizer/rules/CMakeLists.txt
query_optimizer/rules/EliminateEmptyNode.cpp

This PR fixed a bug introduced in #342 that incorrectly reduces an aggregate query on an empty table into a temp table scan. Ironically, `quickstep_cli_tests_commandexecutor_analyze` does not proof the correctness of the rule because the `\analyze` command does not set stats due to the bug mentioned before.
In other words, we could easily reproduce the bug:
```
CREATE TABLE r (a int);
\analyze r
SELECT COUNT(*) FROM r;  // this produce nothing (in 0 row), instead of a ZERO (in 1 row).
```
This fix transforms an aggregate query correctly, and adds more tests.

Fixed the bug regarding EliminateEmptyNode on an aggregate query.

---

cli/tests/command_executor/Analyze.test
query_optimizer/rules/EliminateEmptyNode.cpp

This PR fixed a bug regarding `EliminateEmptyNode` and `InsertSelection` that could be easily reproduced as the following:
```
CREATE TABLE temp (a int);
\analyze
INSERT INTO temp SELECT i FROM generate_series(1, 100) AS gs(i);
```
The problem is that `InsertSelection` allows the destination table to be empty, but the rule does not catch that.

Fixed the bug regarding EliminateEmptyNode and InsertSelection.

---

expressions/scalar/ScalarCaseExpression.cpp
expressions/scalar/ScalarCaseExpression.hpp
expressions/scalar/tests/ScalarCaseExpression_unittest.cpp

This PR does the following:
1. Moved the static methods into the cpp file.
1. Added a fast path for `getAllValuesForJoin`, similar to other existing methods.
1. Added more unit tests to cover the join cases with a static branch.
1. Removed a unnecessary overridden virtual function `getRelationIdForValueAccessor`.

Refactored ScalarCaseExpression.

---

cli/tests/command_executor/Analyze.test
query_optimizer/physical/Aggregate.cpp
query_optimizer/physical/Aggregate.hpp
query_optimizer/physical/CMakeLists.txt
query_optimizer/rules/EliminateEmptyNode.cpp

This PR fixed for the case where the only one child of the union-all query is non-empty, and the child has a non-AttributeReference project expression:
```
SELECT 1 AS a FROM not_empty
UNION ALL
SELECT 0 AS a FROM empty;
```

Fixed the union-all elimiation case where some project expression is not an AttributeReference.
